////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit.csv;

import com.garmin.fit.*;
import com.garmin.fit.test.Tests;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.File;

public class CSVTool {
   public static void main(String args[]) {
      String in = "";
      String out = "";
      boolean fitToCsv = false;
      boolean csvToFit = false;
      boolean test = false;
      boolean checkIntegrity = false;
      int arg = 0;

      System.out.printf("FIT CSV Tool %d.%d.%d.%d\n", Fit.PROTOCOL_VERSION_MAJOR, Fit.PROTOCOL_VERSION_MINOR, Fit.PROFILE_VERSION_MAJOR, Fit.PROFILE_VERSION_MINOR);

      while (arg < args.length) {
         if (args[arg].equals("-b")) {
            if ((args.length - arg) < 3) {
               printUsage();
               return;
            }

            fitToCsv = true;
            in = args[arg + 1];
            out = args[arg + 2];

            arg += 2;
         } else if (args[arg].equals("-c")) {
            if ((args.length - arg) < 3) {
               printUsage();
               return;
            }

            csvToFit = true;
            in = args[arg + 1];
            out = args[arg + 2];
         } else if (args[arg].equals("-t")) {
            test = true;
         } else if (args[arg].equals("-d")) {
            Fit.debug = true;
            test = true;
         } else if (args[arg].equals("-i")) {
            checkIntegrity = true;
         }
         
         arg++;
      }

      if (fitToCsv) {
         if ((out.length() >= 4) && (out.substring(out.length()-4, out.length()).compareTo(".csv") == 0))
            out = out.substring(0, out.length()-4); // Remove .csv extension.
         
         if (checkIntegrity) {
            try {
               if (!Decode.checkIntegrity((InputStream) new FileInputStream(in)))
                  throw new RuntimeException("FIT file integrity failure.");
            } catch (java.io.IOException e) {
               throw new RuntimeException(e);
            }
         }

         if (test) {
            Tests tests = new Tests();
            System.out.println("Running FIT verification tests...");
            if (tests.run(in))
               System.out.println("Passed FIT verification.");
            else
               System.out.println("Failed FIT verification.");
         }

         try {
            Decode decode = new Decode();
            MesgBroadcaster broadcaster = new MesgBroadcaster(decode);
            MesgCSVWriter mesgWriter = new MesgCSVWriter(out + ".csv");
            RecordCSVWriter recordWriter = new RecordCSVWriter(out + "_records.csv"); 
            LapCSVWriter lapWriter = new LapCSVWriter(out + "_laps.csv"); 
            SessionCSVWriter sessionWriter = new SessionCSVWriter(out + "_sessions.csv"); 

            decode.addListener((MesgDefinitionListener) mesgWriter);
            decode.addListener((MesgListener) mesgWriter);
            broadcaster.addListener((RecordMesgListener)recordWriter);
            broadcaster.addListener((MesgWithEventListener)recordWriter);
            broadcaster.addListener(lapWriter);
            broadcaster.addListener(sessionWriter);

            broadcaster.run((InputStream) new FileInputStream(in));
            
            mesgWriter.close();
            recordWriter.close();
            lapWriter.close();
            sessionWriter.close();
         } catch (java.io.IOException e) {
            throw new RuntimeException(e);
         }

         System.out.printf("FIT binary file %s decoded to %s*.csv files.\n", in, out);
      } else if (csvToFit) {
         try {
            FileEncoder encoder = new FileEncoder(new File(out));
            if (!CSVReader.read((InputStream) new FileInputStream(in), encoder, encoder))
               throw new RuntimeException("FIT encoding error.");
            encoder.close();
            
            System.out.printf("%s encoded into FIT binary file %s.\n", in, out);
         } catch (java.io.IOException e) {
            throw new RuntimeException(e);
         }
      } else {
         printUsage();
      }
   }

   private static void printUsage() {
      System.out.println("Usage: java -jar FitCSVTool.jar -b|-c <INPUT FILE> <OUTPUT FILE>");
      System.out.println("      -b <FIT FILE> <CSV FILE>  FIT binary to CSV.");
      System.out.println("      -c <CSV FILE> <FIT FILE>  CSV to FIT binary.");
      System.out.println("      -t Enable file verification tests.");
      System.out.println("      -d Enable debug output (also enables file verification tests).");
      System.out.println("      -i Check integrity of FIT file before decoding.");
      }
}