//>>built
define("tourbook/search/nls/SearchApp_ROOT",{"dojo/cldr/nls/number":{scientificFormat:"#E0","currencySpacing-afterCurrency-currencyMatch":"[:^S:]",infinity:"\u221e",superscriptingExponent:"\u00d7",list:";",percentSign:"%",minusSign:"-","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]",_localized:{da:1,"pt-pt":1,es:1,hu:1,de:1,sk:1,sl:1,pl:1,"zh-hk":1,"zh-hant":1,pt:1,ca:1,sv:1,"zh-tw":1,ar:1,fi:1,ro:1,nb:1,ru:1,zh:1,"fr-ch":1,fr:1,it:1,th:1,he:1,cs:1,nl:1,"en-au":1,el:1,tr:1,ko:1,en:1,
ja:1},"decimalFormat-short":"000T","currencySpacing-afterCurrency-insertBetween":"\u00a0",nan:"NaN",plusSign:"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]",currencyFormat:"\u00a4\u00a0#,##0.00","currencySpacing-beforeCurrency-currencyMatch":"[:^S:]",perMille:"\u2030",group:",",percentFormat:"#,##0%","decimalFormat-long":"000T",decimalFormat:"#,##0.###",decimal:".","currencySpacing-beforeCurrency-insertBetween":"\u00a0",exponential:"E"},"tourbook/search/nls/Messages":{Search_Options_Dialog_Header:"Search Options",
Search_Validation_SearchFilter:"Nothing can be found with these search options.",Search_Options_Checkbox_ShowContentTour:"Tours",Search_App_Action_StartSearch_Tooltip:"Start searching.",Search_Options_Checkbox_ShowContentAll:"All",Search_Options_Group_Sorting:"Sorting",Search_Options_Group_Result:"Result",Search_Options_Checkbox_ShowContentWaypoint:"Waypoints",Search_App_Action_SearchOptions_Tooltip:"Search Options.",Search_Options_Radio_SortDescending:"Descending",Search_Options_Checkbox_EaseSearching_Tooltip:"\x3cb\x3e* Wildcard Search\x3c/b\x3e\x3cbr\x3eWhen \x3ci\x3eUse ease searching\x3c/i\x3e is selected, a * wildcard is appended to the search text, this is done internally which is not visible.\x3cbr\x3e\x3cbr\x3e\x3cb\x3eExtended Search\x3c/b\x3e\x3cbr\x3eIt can be helpfull to deactivate \x3ci\x3eUse ease searching\x3c/i\x3e when doing a search with Lucene query parser options.",
Search_Options_Checkbox_ShowDateTime:"Show date/time",Search_App_Label_Status_Tooltip:"Number of search results - Search time",Search_Options_Action_RestoreDefaults:"Restore Defaults",_localized:{de:1,es:1,cs:1,it:1,fr:1,nl:1},Search_App_Tooltip:"\x3cb\x3eWildcard Search\x3c/b\x3e\x3cbr\x3eA search can also be done with * or ? wildcards and other features, read more details in the \x3ca href\x3d'{0}'\x3eLucene query parser description.\x3c/a\x3e\x3cbr\x3e\x3cbr\x3eLucene is the internal used search engine.",
Search_Options_Checkbox_ShowLuceneDocId:"Show Lucene doc ID",Search_Grid_Label_NoDataMessage:"No search results found.",Search_App_Action_EditMarker:"Edit Marker",Search_Options_Group_Content:"What should be searched?",Search_Options_Label_SortAscending:"By Date ",Search_Options_Radio_SortAscending:"Ascending",Search_Options_Checkbox_ShowItemNumber:"Show item number",Search_Options_Checkbox_ShowContentMarker:"Markers",Search_App_Action_EditTour:"Edit Tour",Search_Options_Checkbox_EaseSearching:"Use ease searching",
Search_App_Text_Search_PlaceHolder:"Search Tours, Marker and Waypoints"},"dijit/form/nls/ComboBox":{previousMessage:"Previous choices",_localized:{hr:1,da:1,"pt-pt":1,es:1,hu:1,de:1,sk:1,sl:1,pl:1,pt:1,ca:1,sv:1,id:1,"zh-tw":1,ar:1,uk:1,fi:1,ro:1,az:1,nb:1,ru:1,zh:1,fr:1,it:1,th:1,he:1,cs:1,bg:1,nl:1,kk:1,el:1,tr:1,ko:1,ja:1},nextMessage:"More choices"},"dijit/nls/loading":{_localized:{hr:1,da:1,"pt-pt":1,es:1,hu:1,de:1,sk:1,sl:1,pl:1,pt:1,ca:1,sv:1,id:1,"zh-tw":1,ar:1,uk:1,fi:1,ro:1,az:1,nb:1,zh:1,
ru:1,fr:1,th:1,it:1,he:1,cs:1,bg:1,nl:1,kk:1,el:1,tr:1,ko:1,ja:1},loadingState:"Loading...",errorState:"Sorry, an error occurred"},"dijit/form/nls/validate":{invalidMessage:"The value entered is not valid.",rangeMessage:"This value is out of range.",_localized:{hr:1,da:1,"pt-pt":1,es:1,hu:1,de:1,sk:1,sl:1,pl:1,pt:1,ca:1,sv:1,id:1,"zh-tw":1,ar:1,uk:1,fi:1,ro:1,az:1,nb:1,zh:1,ru:1,fr:1,th:1,it:1,he:1,cs:1,bg:1,kk:1,nl:1,el:1,tr:1,ko:1,ja:1},missingMessage:"This value is required."},"dijit/nls/common":{buttonOk:"OK",
buttonCancel:"Cancel",_localized:{hr:1,da:1,"pt-pt":1,es:1,hu:1,de:1,sk:1,sl:1,pl:1,pt:1,ca:1,sv:1,id:1,"zh-tw":1,ar:1,uk:1,fi:1,ro:1,az:1,nb:1,zh:1,ru:1,fr:1,it:1,th:1,he:1,cs:1,bg:1,kk:1,nl:1,el:1,ko:1,tr:1,ja:1},buttonSave:"Save",itemClose:"Close"}});
//# sourceMappingURL=SearchApp_ROOT.js.map