////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public class CourseCapabilities {
   public static final long PROCESSED = 0x00000001; 
   public static final long VALID = 0x00000002; 
   public static final long TIME = 0x00000004; 
   public static final long DISTANCE = 0x00000008; 
   public static final long POSITION = 0x00000010; 
   public static final long HEART_RATE = 0x00000020; 
   public static final long POWER = 0x00000040; 
   public static final long CADENCE = 0x00000080; 
   public static final long TRAINING = 0x00000100; 
   public static final long NAVIGATION = 0x00000200; 
   public static final long INVALID = Fit.UINT32Z_INVALID;








}
