////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public class DeviceInfoMesg extends Mesg {


   public DeviceInfoMesg() {
      super(Factory.createMesg(MesgNum.DEVICE_INFO));
   }

   public DeviceInfoMesg(final Mesg mesg) {
      super(mesg);
   }
   
   /**
    * Get timestamp field
    * Units: s
    *
    * @return timestamp
    */
   public DateTime getTimestamp() {
      return timestampToDateTime(getFieldLongValue(253));
   }

   /**
    * Set timestamp field
    * Units: s
    *
    * @param timestamp
    */
   public void setTimestamp(DateTime timestamp) {
      setFieldValue("timestamp", timestamp.getTimestamp());
   }   
   /**
    * Get device_index field
    *
    * @return device_index
    */
   public Short getDeviceIndex() {
      return getFieldShortValue(0);
   }

   /**
    * Set device_index field
    *
    * @param deviceIndex
    */
   public void setDeviceIndex(Short deviceIndex) {
      setFieldValue("device_index", deviceIndex);
   }   
   /**
    * Get device_type field
    *
    * @return device_type
    */
   public Short getDeviceType() {
      return getFieldShortValue(1);
   }

   /**
    * Set device_type field
    *
    * @param deviceType
    */
   public void setDeviceType(Short deviceType) {
      setFieldValue("device_type", deviceType);
   }   
   /**
    * Get manufacturer field
    *
    * @return manufacturer
    */
   public Integer getManufacturer() {
      return getFieldIntegerValue(2);
   }

   /**
    * Set manufacturer field
    *
    * @param manufacturer
    */
   public void setManufacturer(Integer manufacturer) {
      setFieldValue("manufacturer", manufacturer);
   }   
   /**
    * Get serial_number field
    *
    * @return serial_number
    */
   public Long getSerialNumber() {
      return getFieldLongValue(3);
   }

   /**
    * Set serial_number field
    *
    * @param serialNumber
    */
   public void setSerialNumber(Long serialNumber) {
      setFieldValue("serial_number", serialNumber);
   }   
   /**
    * Get product field
    *
    * @return product
    */
   public Integer getProduct() {
      return getFieldIntegerValue(4);
   }

   /**
    * Set product field
    *
    * @param product
    */
   public void setProduct(Integer product) {
      setFieldValue("product", product);
   }   
   /**
    * Get software_version field
    *
    * @return software_version
    */
   public Float getSoftwareVersion() {
      return getFieldFloatValue(5);
   }

   /**
    * Set software_version field
    *
    * @param softwareVersion
    */
   public void setSoftwareVersion(Float softwareVersion) {
      setFieldValue("software_version", softwareVersion);
   }   
   /**
    * Get hardware_version field
    *
    * @return hardware_version
    */
   public Short getHardwareVersion() {
      return getFieldShortValue(6);
   }

   /**
    * Set hardware_version field
    *
    * @param hardwareVersion
    */
   public void setHardwareVersion(Short hardwareVersion) {
      setFieldValue("hardware_version", hardwareVersion);
   }   
   /**
    * Get cum_operating_time field
    * Units: s
    * Comment: Reset by new battery or charge.
    *
    * @return cum_operating_time
    */
   public Long getCumOperatingTime() {
      return getFieldLongValue(7);
   }

   /**
    * Set cum_operating_time field
    * Units: s
    * Comment: Reset by new battery or charge.
    *
    * @param cumOperatingTime
    */
   public void setCumOperatingTime(Long cumOperatingTime) {
      setFieldValue("cum_operating_time", cumOperatingTime);
   }   
   /**
    * Get battery_voltage field
    * Units: V
    *
    * @return battery_voltage
    */
   public Float getBatteryVoltage() {
      return getFieldFloatValue(10);
   }

   /**
    * Set battery_voltage field
    * Units: V
    *
    * @param batteryVoltage
    */
   public void setBatteryVoltage(Float batteryVoltage) {
      setFieldValue("battery_voltage", batteryVoltage);
   }   
   /**
    * Get battery_status field
    *
    * @return battery_status
    */
   public Short getBatteryStatus() {
      return getFieldShortValue(11);
   }

   /**
    * Set battery_status field
    *
    * @param batteryStatus
    */
   public void setBatteryStatus(Short batteryStatus) {
      setFieldValue("battery_status", batteryStatus);
   }

}
