////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public class EventMesg extends Mesg implements MesgWithEvent {


   public EventMesg() {
      super(Factory.createMesg(MesgNum.EVENT));
   }

   public EventMesg(final Mesg mesg) {
      super(mesg);
   }
   
   /**
    * Get timestamp field
    * Units: s
    *
    * @return timestamp
    */
   public DateTime getTimestamp() {
      return timestampToDateTime(getFieldLongValue(253));
   }

   /**
    * Set timestamp field
    * Units: s
    *
    * @param timestamp
    */
   public void setTimestamp(DateTime timestamp) {
      setFieldValue("timestamp", timestamp.getTimestamp());
   }   
   /**
    * Get event field
    *
    * @return event
    */
   public Event getEvent() {
      Short value = getFieldShortValue(0);
     if (value == null)
        return null;
      return Event.getByValue(value);
   }

   /**
    * Set event field
    *
    * @param event
    */
   public void setEvent(Event event) {
      setFieldValue("event", event.value);
   }   
   /**
    * Get event_type field
    *
    * @return event_type
    */
   public EventType getEventType() {
      Short value = getFieldShortValue(1);
     if (value == null)
        return null;
      return EventType.getByValue(value);
   }

   /**
    * Set event_type field
    *
    * @param eventType
    */
   public void setEventType(EventType eventType) {
      setFieldValue("event_type", eventType.value);
   }   
   /**
    * Get data16 field
    *
    * @return data16
    */
   public Integer getData16() {
      return getFieldIntegerValue(2);
   }

   /**
    * Set data16 field
    *
    * @param data16
    */
   public void setData16(Integer data16) {
      setFieldValue("data16", data16);
   }   
   /**
    * Get data field
    *
    * @return data
    */
   public Long getData() {
      return getFieldLongValue(3);
   }

   /**
    * Set data field
    *
    * @param data
    */
   public void setData(Long data) {
      setFieldValue("data", data);
   }   
   /**
    * Get timer_trigger field
    *
    * @return timer_trigger
    */
   public TimerTrigger getTimerTrigger() {
      Short value = getFieldShortValue("timer_trigger");
     if (value == null)
        return null;
      return TimerTrigger.getByValue(value);
   }

   /**
    * Set timer_trigger field
    *
    * @param timerTrigger
    */
   public void setTimerTrigger(TimerTrigger timerTrigger) {
      setFieldValue("timer_trigger", timerTrigger.value);
   }   
   /**
    * Get course_point_index field
    *
    * @return course_point_index
    */
   public Integer getCoursePointIndex() {
      return getFieldIntegerValue("course_point_index");
   }

   /**
    * Set course_point_index field
    *
    * @param coursePointIndex
    */
   public void setCoursePointIndex(Integer coursePointIndex) {
      setFieldValue("course_point_index", coursePointIndex);
   }   
   /**
    * Get battery_level field
    * Units: V
    *
    * @return battery_level
    */
   public Float getBatteryLevel() {
      return getFieldFloatValue("battery_level");
   }

   /**
    * Set battery_level field
    * Units: V
    *
    * @param batteryLevel
    */
   public void setBatteryLevel(Float batteryLevel) {
      setFieldValue("battery_level", batteryLevel);
   }   
   /**
    * Get virtual_partner_speed field
    * Units: m/s
    *
    * @return virtual_partner_speed
    */
   public Float getVirtualPartnerSpeed() {
      return getFieldFloatValue("virtual_partner_speed");
   }

   /**
    * Set virtual_partner_speed field
    * Units: m/s
    *
    * @param virtualPartnerSpeed
    */
   public void setVirtualPartnerSpeed(Float virtualPartnerSpeed) {
      setFieldValue("virtual_partner_speed", virtualPartnerSpeed);
   }   
   /**
    * Get hr_high_alert field
    * Units: bpm
    *
    * @return hr_high_alert
    */
   public Short getHrHighAlert() {
      return getFieldShortValue("hr_high_alert");
   }

   /**
    * Set hr_high_alert field
    * Units: bpm
    *
    * @param hrHighAlert
    */
   public void setHrHighAlert(Short hrHighAlert) {
      setFieldValue("hr_high_alert", hrHighAlert);
   }   
   /**
    * Get hr_low_alert field
    * Units: bpm
    *
    * @return hr_low_alert
    */
   public Short getHrLowAlert() {
      return getFieldShortValue("hr_low_alert");
   }

   /**
    * Set hr_low_alert field
    * Units: bpm
    *
    * @param hrLowAlert
    */
   public void setHrLowAlert(Short hrLowAlert) {
      setFieldValue("hr_low_alert", hrLowAlert);
   }   
   /**
    * Get speed_high_alert field
    * Units: m/s
    *
    * @return speed_high_alert
    */
   public Float getSpeedHighAlert() {
      return getFieldFloatValue("speed_high_alert");
   }

   /**
    * Set speed_high_alert field
    * Units: m/s
    *
    * @param speedHighAlert
    */
   public void setSpeedHighAlert(Float speedHighAlert) {
      setFieldValue("speed_high_alert", speedHighAlert);
   }   
   /**
    * Get speed_low_alert field
    * Units: m/s
    *
    * @return speed_low_alert
    */
   public Float getSpeedLowAlert() {
      return getFieldFloatValue("speed_low_alert");
   }

   /**
    * Set speed_low_alert field
    * Units: m/s
    *
    * @param speedLowAlert
    */
   public void setSpeedLowAlert(Float speedLowAlert) {
      setFieldValue("speed_low_alert", speedLowAlert);
   }   
   /**
    * Get cad_high_alert field
    * Units: rpm
    *
    * @return cad_high_alert
    */
   public Integer getCadHighAlert() {
      return getFieldIntegerValue("cad_high_alert");
   }

   /**
    * Set cad_high_alert field
    * Units: rpm
    *
    * @param cadHighAlert
    */
   public void setCadHighAlert(Integer cadHighAlert) {
      setFieldValue("cad_high_alert", cadHighAlert);
   }   
   /**
    * Get cad_low_alert field
    * Units: rpm
    *
    * @return cad_low_alert
    */
   public Integer getCadLowAlert() {
      return getFieldIntegerValue("cad_low_alert");
   }

   /**
    * Set cad_low_alert field
    * Units: rpm
    *
    * @param cadLowAlert
    */
   public void setCadLowAlert(Integer cadLowAlert) {
      setFieldValue("cad_low_alert", cadLowAlert);
   }   
   /**
    * Get power_high_alert field
    * Units: watts
    *
    * @return power_high_alert
    */
   public Integer getPowerHighAlert() {
      return getFieldIntegerValue("power_high_alert");
   }

   /**
    * Set power_high_alert field
    * Units: watts
    *
    * @param powerHighAlert
    */
   public void setPowerHighAlert(Integer powerHighAlert) {
      setFieldValue("power_high_alert", powerHighAlert);
   }   
   /**
    * Get power_low_alert field
    * Units: watts
    *
    * @return power_low_alert
    */
   public Integer getPowerLowAlert() {
      return getFieldIntegerValue("power_low_alert");
   }

   /**
    * Set power_low_alert field
    * Units: watts
    *
    * @param powerLowAlert
    */
   public void setPowerLowAlert(Integer powerLowAlert) {
      setFieldValue("power_low_alert", powerLowAlert);
   }   
   /**
    * Get time_duration_alert field
    * Units: s
    *
    * @return time_duration_alert
    */
   public Float getTimeDurationAlert() {
      return getFieldFloatValue("time_duration_alert");
   }

   /**
    * Set time_duration_alert field
    * Units: s
    *
    * @param timeDurationAlert
    */
   public void setTimeDurationAlert(Float timeDurationAlert) {
      setFieldValue("time_duration_alert", timeDurationAlert);
   }   
   /**
    * Get distance_duration_alert field
    * Units: m
    *
    * @return distance_duration_alert
    */
   public Float getDistanceDurationAlert() {
      return getFieldFloatValue("distance_duration_alert");
   }

   /**
    * Set distance_duration_alert field
    * Units: m
    *
    * @param distanceDurationAlert
    */
   public void setDistanceDurationAlert(Float distanceDurationAlert) {
      setFieldValue("distance_duration_alert", distanceDurationAlert);
   }   
   /**
    * Get calorie_duration_alert field
    * Units: calories
    *
    * @return calorie_duration_alert
    */
   public Long getCalorieDurationAlert() {
      return getFieldLongValue("calorie_duration_alert");
   }

   /**
    * Set calorie_duration_alert field
    * Units: calories
    *
    * @param calorieDurationAlert
    */
   public void setCalorieDurationAlert(Long calorieDurationAlert) {
      setFieldValue("calorie_duration_alert", calorieDurationAlert);
   }   
   /**
    * Get fitness_equipment_state field
    *
    * @return fitness_equipment_state
    */
   public FitnessEquipmentState getFitnessEquipmentState() {
      Short value = getFieldShortValue("fitness_equipment_state");
     if (value == null)
        return null;
      return FitnessEquipmentState.getByValue(value);
   }

   /**
    * Set fitness_equipment_state field
    *
    * @param fitnessEquipmentState
    */
   public void setFitnessEquipmentState(FitnessEquipmentState fitnessEquipmentState) {
      setFieldValue("fitness_equipment_state", fitnessEquipmentState.value);
   }   
   /**
    * Get event_group field
    *
    * @return event_group
    */
   public Short getEventGroup() {
      return getFieldShortValue(4);
   }

   /**
    * Set event_group field
    *
    * @param eventGroup
    */
   public void setEventGroup(Short eventGroup) {
      setFieldValue("event_group", eventGroup);
   }

}
