////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public class FileCapabilitiesMesg extends Mesg {


   public FileCapabilitiesMesg() {
      super(Factory.createMesg(MesgNum.FILE_CAPABILITIES));
   }

   public FileCapabilitiesMesg(final Mesg mesg) {
      super(mesg);
   }
   
   /**
    * Get message_index field
    *
    * @return message_index
    */
   public Integer getMessageIndex() {
      return getFieldIntegerValue(254);
   }

   /**
    * Set message_index field
    *
    * @param messageIndex
    */
   public void setMessageIndex(Integer messageIndex) {
      setFieldValue("message_index", messageIndex);
   }   
   /**
    * Get type field
    *
    * @return type
    */
   public File getType() {
      Short value = getFieldShortValue(0);
     if (value == null)
        return null;
      return File.getByValue(value);
   }

   /**
    * Set type field
    *
    * @param type
    */
   public void setType(File type) {
      setFieldValue("type", type.value);
   }   
   /**
    * Get flags field
    *
    * @return flags
    */
   public Short getFlags() {
      return getFieldShortValue(1);
   }

   /**
    * Set flags field
    *
    * @param flags
    */
   public void setFlags(Short flags) {
      setFieldValue("flags", flags);
   }   
   /**
    * Get directory field
    *
    * @return directory
    */
   public String getDirectory() {
      return getFieldStringValue(2);
   }

   /**
    * Set directory field
    *
    * @param directory
    */
   public void setDirectory(String directory) {
      setFieldValue("directory", directory);
   }   
   /**
    * Get max_count field
    *
    * @return max_count
    */
   public Integer getMaxCount() {
      return getFieldIntegerValue(3);
   }

   /**
    * Set max_count field
    *
    * @param maxCount
    */
   public void setMaxCount(Integer maxCount) {
      setFieldValue("max_count", maxCount);
   }   
   /**
    * Get max_size field
    * Units: bytes
    *
    * @return max_size
    */
   public Long getMaxSize() {
      return getFieldLongValue(4);
   }

   /**
    * Set max_size field
    * Units: bytes
    *
    * @param maxSize
    */
   public void setMaxSize(Long maxSize) {
      setFieldValue("max_size", maxSize);
   }

}
