////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public enum GoalRecurrence {
   OFF((short)0),   
   DAILY((short)1),   
   WEEKLY((short)2),   
   MONTHLY((short)3),   
   YEARLY((short)4),   
   CUSTOM((short)5),   
   INVALID((short)255);


   protected short value;




   private GoalRecurrence(short value) {
     this.value = value;
   }

   protected static GoalRecurrence getByValue(final Short value) {
      for (final GoalRecurrence type : GoalRecurrence.values()) {
         if (value == type.value)
            return type;
      }

      return GoalRecurrence.INVALID;
   }

   public short getValue() {
      return value;
   }


}
