////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public class MesgNum {
   public static final int FILE_ID = 0; 
   public static final int CAPABILITIES = 1; 
   public static final int DEVICE_SETTINGS = 2; 
   public static final int USER_PROFILE = 3; 
   public static final int HRM_PROFILE = 4; 
   public static final int SDM_PROFILE = 5; 
   public static final int BIKE_PROFILE = 6; 
   public static final int ZONES_TARGET = 7; 
   public static final int HR_ZONE = 8; 
   public static final int POWER_ZONE = 9; 
   public static final int MET_ZONE = 10; 
   public static final int SPORT = 12; 
   public static final int GOAL = 15; 
   public static final int SESSION = 18; 
   public static final int LAP = 19; 
   public static final int RECORD = 20; 
   public static final int EVENT = 21; 
   public static final int DEVICE_INFO = 23; 
   public static final int WORKOUT = 26; 
   public static final int WORKOUT_STEP = 27; 
   public static final int WEIGHT_SCALE = 30; 
   public static final int COURSE = 31; 
   public static final int COURSE_POINT = 32; 
   public static final int TOTALS = 33; 
   public static final int ACTIVITY = 34; 
   public static final int SOFTWARE = 35; 
   public static final int FILE_CAPABILITIES = 37; 
   public static final int MESG_CAPABILITIES = 38; 
   public static final int FIELD_CAPABILITIES = 39; 
   public static final int FILE_CREATOR = 49; 
   public static final int BLOOD_PRESSURE = 51; 
   public static final int MFG_RANGE_MIN = 0xFF00; // 0xFF00 - 0xFFFE reserved for manufacturer specific messages 
   public static final int MFG_RANGE_MAX = 0xFFFE; // 0xFF00 - 0xFFFE reserved for manufacturer specific messages 
   public static final int INVALID = Fit.UINT16_INVALID;








}
