////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public class SdmProfileMesg extends Mesg {


   public SdmProfileMesg() {
      super(Factory.createMesg(MesgNum.SDM_PROFILE));
   }

   public SdmProfileMesg(final Mesg mesg) {
      super(mesg);
   }
   
   /**
    * Get message_index field
    *
    * @return message_index
    */
   public Integer getMessageIndex() {
      return getFieldIntegerValue(254);
   }

   /**
    * Set message_index field
    *
    * @param messageIndex
    */
   public void setMessageIndex(Integer messageIndex) {
      setFieldValue("message_index", messageIndex);
   }   
   /**
    * Get enabled field
    *
    * @return enabled
    */
   public Bool getEnabled() {
      Short value = getFieldShortValue(0);
     if (value == null)
        return null;
      return Bool.getByValue(value);
   }

   /**
    * Set enabled field
    *
    * @param enabled
    */
   public void setEnabled(Bool enabled) {
      setFieldValue("enabled", enabled.value);
   }   
   /**
    * Get sdm_ant_id field
    *
    * @return sdm_ant_id
    */
   public Integer getSdmAntId() {
      return getFieldIntegerValue(1);
   }

   /**
    * Set sdm_ant_id field
    *
    * @param sdmAntId
    */
   public void setSdmAntId(Integer sdmAntId) {
      setFieldValue("sdm_ant_id", sdmAntId);
   }   
   /**
    * Get sdm_cal_factor field
    * Units: %
    *
    * @return sdm_cal_factor
    */
   public Float getSdmCalFactor() {
      return getFieldFloatValue(2);
   }

   /**
    * Set sdm_cal_factor field
    * Units: %
    *
    * @param sdmCalFactor
    */
   public void setSdmCalFactor(Float sdmCalFactor) {
      setFieldValue("sdm_cal_factor", sdmCalFactor);
   }   
   /**
    * Get odometer field
    * Units: m
    *
    * @return odometer
    */
   public Float getOdometer() {
      return getFieldFloatValue(3);
   }

   /**
    * Set odometer field
    * Units: m
    *
    * @param odometer
    */
   public void setOdometer(Float odometer) {
      setFieldValue("odometer", odometer);
   }   
   /**
    * Get speed_source field
    * Comment: Use footpod for speed source instead of GPS
    *
    * @return speed_source
    */
   public Bool getSpeedSource() {
      Short value = getFieldShortValue(4);
     if (value == null)
        return null;
      return Bool.getByValue(value);
   }

   /**
    * Set speed_source field
    * Comment: Use footpod for speed source instead of GPS
    *
    * @param speedSource
    */
   public void setSpeedSource(Bool speedSource) {
      setFieldValue("speed_source", speedSource.value);
   }

}
