////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public class WorkoutStepMesg extends Mesg {


   public WorkoutStepMesg() {
      super(Factory.createMesg(MesgNum.WORKOUT_STEP));
   }

   public WorkoutStepMesg(final Mesg mesg) {
      super(mesg);
   }
   
   /**
    * Get message_index field
    *
    * @return message_index
    */
   public Integer getMessageIndex() {
      return getFieldIntegerValue(254);
   }

   /**
    * Set message_index field
    *
    * @param messageIndex
    */
   public void setMessageIndex(Integer messageIndex) {
      setFieldValue("message_index", messageIndex);
   }   
   /**
    * Get wkt_step_name field
    *
    * @return wkt_step_name
    */
   public String getWktStepName() {
      return getFieldStringValue(0);
   }

   /**
    * Set wkt_step_name field
    *
    * @param wktStepName
    */
   public void setWktStepName(String wktStepName) {
      setFieldValue("wkt_step_name", wktStepName);
   }   
   /**
    * Get duration_type field
    *
    * @return duration_type
    */
   public WktStepDuration getDurationType() {
      Short value = getFieldShortValue(1);
     if (value == null)
        return null;
      return WktStepDuration.getByValue(value);
   }

   /**
    * Set duration_type field
    *
    * @param durationType
    */
   public void setDurationType(WktStepDuration durationType) {
      setFieldValue("duration_type", durationType.value);
   }   
   /**
    * Get duration_value field
    *
    * @return duration_value
    */
   public Long getDurationValue() {
      return getFieldLongValue(2);
   }

   /**
    * Set duration_value field
    *
    * @param durationValue
    */
   public void setDurationValue(Long durationValue) {
      setFieldValue("duration_value", durationValue);
   }   
   /**
    * Get duration_time field
    * Units: s
    *
    * @return duration_time
    */
   public Float getDurationTime() {
      return getFieldFloatValue("duration_time");
   }

   /**
    * Set duration_time field
    * Units: s
    *
    * @param durationTime
    */
   public void setDurationTime(Float durationTime) {
      setFieldValue("duration_time", durationTime);
   }   
   /**
    * Get duration_distance field
    * Units: m
    *
    * @return duration_distance
    */
   public Float getDurationDistance() {
      return getFieldFloatValue("duration_distance");
   }

   /**
    * Set duration_distance field
    * Units: m
    *
    * @param durationDistance
    */
   public void setDurationDistance(Float durationDistance) {
      setFieldValue("duration_distance", durationDistance);
   }   
   /**
    * Get duration_hr field
    * Units: % or bpm
    *
    * @return duration_hr
    */
   public Long getDurationHr() {
      return getFieldLongValue("duration_hr");
   }

   /**
    * Set duration_hr field
    * Units: % or bpm
    *
    * @param durationHr
    */
   public void setDurationHr(Long durationHr) {
      setFieldValue("duration_hr", durationHr);
   }   
   /**
    * Get duration_calories field
    * Units: calories
    *
    * @return duration_calories
    */
   public Long getDurationCalories() {
      return getFieldLongValue("duration_calories");
   }

   /**
    * Set duration_calories field
    * Units: calories
    *
    * @param durationCalories
    */
   public void setDurationCalories(Long durationCalories) {
      setFieldValue("duration_calories", durationCalories);
   }   
   /**
    * Get duration_step field
    *
    * @return duration_step
    */
   public Long getDurationStep() {
      return getFieldLongValue("duration_step");
   }

   /**
    * Set duration_step field
    *
    * @param durationStep
    */
   public void setDurationStep(Long durationStep) {
      setFieldValue("duration_step", durationStep);
   }   
   /**
    * Get duration_power field
    * Units: % or watts
    *
    * @return duration_power
    */
   public Long getDurationPower() {
      return getFieldLongValue("duration_power");
   }

   /**
    * Set duration_power field
    * Units: % or watts
    *
    * @param durationPower
    */
   public void setDurationPower(Long durationPower) {
      setFieldValue("duration_power", durationPower);
   }   
   /**
    * Get target_type field
    *
    * @return target_type
    */
   public WktStepTarget getTargetType() {
      Short value = getFieldShortValue(3);
     if (value == null)
        return null;
      return WktStepTarget.getByValue(value);
   }

   /**
    * Set target_type field
    *
    * @param targetType
    */
   public void setTargetType(WktStepTarget targetType) {
      setFieldValue("target_type", targetType.value);
   }   
   /**
    * Get target_value field
    *
    * @return target_value
    */
   public Long getTargetValue() {
      return getFieldLongValue(4);
   }

   /**
    * Set target_value field
    *
    * @param targetValue
    */
   public void setTargetValue(Long targetValue) {
      setFieldValue("target_value", targetValue);
   }   
   /**
    * Get target_hr_zone field
    *
    * @return target_hr_zone
    */
   public Long getTargetHrZone() {
      return getFieldLongValue("target_hr_zone");
   }

   /**
    * Set target_hr_zone field
    *
    * @param targetHrZone
    */
   public void setTargetHrZone(Long targetHrZone) {
      setFieldValue("target_hr_zone", targetHrZone);
   }   
   /**
    * Get target_power_zone field
    *
    * @return target_power_zone
    */
   public Long getTargetPowerZone() {
      return getFieldLongValue("target_power_zone");
   }

   /**
    * Set target_power_zone field
    *
    * @param targetPowerZone
    */
   public void setTargetPowerZone(Long targetPowerZone) {
      setFieldValue("target_power_zone", targetPowerZone);
   }   
   /**
    * Get repeat_steps field
    *
    * @return repeat_steps
    */
   public Long getRepeatSteps() {
      return getFieldLongValue("repeat_steps");
   }

   /**
    * Set repeat_steps field
    *
    * @param repeatSteps
    */
   public void setRepeatSteps(Long repeatSteps) {
      setFieldValue("repeat_steps", repeatSteps);
   }   
   /**
    * Get repeat_time field
    * Units: s
    *
    * @return repeat_time
    */
   public Float getRepeatTime() {
      return getFieldFloatValue("repeat_time");
   }

   /**
    * Set repeat_time field
    * Units: s
    *
    * @param repeatTime
    */
   public void setRepeatTime(Float repeatTime) {
      setFieldValue("repeat_time", repeatTime);
   }   
   /**
    * Get repeat_distance field
    * Units: m
    *
    * @return repeat_distance
    */
   public Float getRepeatDistance() {
      return getFieldFloatValue("repeat_distance");
   }

   /**
    * Set repeat_distance field
    * Units: m
    *
    * @param repeatDistance
    */
   public void setRepeatDistance(Float repeatDistance) {
      setFieldValue("repeat_distance", repeatDistance);
   }   
   /**
    * Get repeat_calories field
    * Units: calories
    *
    * @return repeat_calories
    */
   public Long getRepeatCalories() {
      return getFieldLongValue("repeat_calories");
   }

   /**
    * Set repeat_calories field
    * Units: calories
    *
    * @param repeatCalories
    */
   public void setRepeatCalories(Long repeatCalories) {
      setFieldValue("repeat_calories", repeatCalories);
   }   
   /**
    * Get repeat_hr field
    * Units: % or bpm
    *
    * @return repeat_hr
    */
   public Long getRepeatHr() {
      return getFieldLongValue("repeat_hr");
   }

   /**
    * Set repeat_hr field
    * Units: % or bpm
    *
    * @param repeatHr
    */
   public void setRepeatHr(Long repeatHr) {
      setFieldValue("repeat_hr", repeatHr);
   }   
   /**
    * Get repeat_power field
    * Units: % or watts
    *
    * @return repeat_power
    */
   public Long getRepeatPower() {
      return getFieldLongValue("repeat_power");
   }

   /**
    * Set repeat_power field
    * Units: % or watts
    *
    * @param repeatPower
    */
   public void setRepeatPower(Long repeatPower) {
      setFieldValue("repeat_power", repeatPower);
   }   
   /**
    * Get custom_target_value_low field
    *
    * @return custom_target_value_low
    */
   public Long getCustomTargetValueLow() {
      return getFieldLongValue(5);
   }

   /**
    * Set custom_target_value_low field
    *
    * @param customTargetValueLow
    */
   public void setCustomTargetValueLow(Long customTargetValueLow) {
      setFieldValue("custom_target_value_low", customTargetValueLow);
   }   
   /**
    * Get custom_target_speed_low field
    * Units: m/s
    *
    * @return custom_target_speed_low
    */
   public Float getCustomTargetSpeedLow() {
      return getFieldFloatValue("custom_target_speed_low");
   }

   /**
    * Set custom_target_speed_low field
    * Units: m/s
    *
    * @param customTargetSpeedLow
    */
   public void setCustomTargetSpeedLow(Float customTargetSpeedLow) {
      setFieldValue("custom_target_speed_low", customTargetSpeedLow);
   }   
   /**
    * Get custom_target_heart_rate_low field
    * Units: % or bpm
    *
    * @return custom_target_heart_rate_low
    */
   public Long getCustomTargetHeartRateLow() {
      return getFieldLongValue("custom_target_heart_rate_low");
   }

   /**
    * Set custom_target_heart_rate_low field
    * Units: % or bpm
    *
    * @param customTargetHeartRateLow
    */
   public void setCustomTargetHeartRateLow(Long customTargetHeartRateLow) {
      setFieldValue("custom_target_heart_rate_low", customTargetHeartRateLow);
   }   
   /**
    * Get custom_target_cadence_low field
    * Units: rpm
    *
    * @return custom_target_cadence_low
    */
   public Long getCustomTargetCadenceLow() {
      return getFieldLongValue("custom_target_cadence_low");
   }

   /**
    * Set custom_target_cadence_low field
    * Units: rpm
    *
    * @param customTargetCadenceLow
    */
   public void setCustomTargetCadenceLow(Long customTargetCadenceLow) {
      setFieldValue("custom_target_cadence_low", customTargetCadenceLow);
   }   
   /**
    * Get custom_target_power_low field
    * Units: % or watts
    *
    * @return custom_target_power_low
    */
   public Long getCustomTargetPowerLow() {
      return getFieldLongValue("custom_target_power_low");
   }

   /**
    * Set custom_target_power_low field
    * Units: % or watts
    *
    * @param customTargetPowerLow
    */
   public void setCustomTargetPowerLow(Long customTargetPowerLow) {
      setFieldValue("custom_target_power_low", customTargetPowerLow);
   }   
   /**
    * Get custom_target_value_high field
    *
    * @return custom_target_value_high
    */
   public Long getCustomTargetValueHigh() {
      return getFieldLongValue(6);
   }

   /**
    * Set custom_target_value_high field
    *
    * @param customTargetValueHigh
    */
   public void setCustomTargetValueHigh(Long customTargetValueHigh) {
      setFieldValue("custom_target_value_high", customTargetValueHigh);
   }   
   /**
    * Get custom_target_speed_high field
    * Units: m/s
    *
    * @return custom_target_speed_high
    */
   public Float getCustomTargetSpeedHigh() {
      return getFieldFloatValue("custom_target_speed_high");
   }

   /**
    * Set custom_target_speed_high field
    * Units: m/s
    *
    * @param customTargetSpeedHigh
    */
   public void setCustomTargetSpeedHigh(Float customTargetSpeedHigh) {
      setFieldValue("custom_target_speed_high", customTargetSpeedHigh);
   }   
   /**
    * Get custom_target_heart_rate_high field
    * Units: % or bpm
    *
    * @return custom_target_heart_rate_high
    */
   public Long getCustomTargetHeartRateHigh() {
      return getFieldLongValue("custom_target_heart_rate_high");
   }

   /**
    * Set custom_target_heart_rate_high field
    * Units: % or bpm
    *
    * @param customTargetHeartRateHigh
    */
   public void setCustomTargetHeartRateHigh(Long customTargetHeartRateHigh) {
      setFieldValue("custom_target_heart_rate_high", customTargetHeartRateHigh);
   }   
   /**
    * Get custom_target_cadence_high field
    * Units: rpm
    *
    * @return custom_target_cadence_high
    */
   public Long getCustomTargetCadenceHigh() {
      return getFieldLongValue("custom_target_cadence_high");
   }

   /**
    * Set custom_target_cadence_high field
    * Units: rpm
    *
    * @param customTargetCadenceHigh
    */
   public void setCustomTargetCadenceHigh(Long customTargetCadenceHigh) {
      setFieldValue("custom_target_cadence_high", customTargetCadenceHigh);
   }   
   /**
    * Get custom_target_power_high field
    * Units: % or watts
    *
    * @return custom_target_power_high
    */
   public Long getCustomTargetPowerHigh() {
      return getFieldLongValue("custom_target_power_high");
   }

   /**
    * Set custom_target_power_high field
    * Units: % or watts
    *
    * @param customTargetPowerHigh
    */
   public void setCustomTargetPowerHigh(Long customTargetPowerHigh) {
      setFieldValue("custom_target_power_high", customTargetPowerHigh);
   }   
   /**
    * Get intensity field
    *
    * @return intensity
    */
   public Intensity getIntensity() {
      Short value = getFieldShortValue(7);
     if (value == null)
        return null;
      return Intensity.getByValue(value);
   }

   /**
    * Set intensity field
    *
    * @param intensity
    */
   public void setIntensity(Intensity intensity) {
      setFieldValue("intensity", intensity.value);
   }

}
