/*******************************************************************************
 * Copyright (C) 2021, 2023 Wolfgang Schramm and Contributors
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA
 *******************************************************************************/
package net.tourbook;

/**
 * Contains image constants which do not need to be translated
 */
public class Images {

   /*
    * These images are currently translated
    */

//   Image_Action_ShowSliderInMap         = map-marker-slider-right-action_it.png
//   Image_Action_ShowSliderInMap_Left    = map-marker-slider-left-action.png
//   Image_Action_ShowStartEndInMap       = map-marker-start-action_it.png

//   Image_Map_MarkerSliderLeft           = map-marker-slider-left_it.png
//   Image_Map_MarkerSliderRight          = map-marker-slider-right_it.png
//   Image_Map_TourEndMarker              = map-marker-end_it.png
//   Image_Map_TourStartMarker            = map-marker-start_it.png

   /*
    * These images are not translated
    */
   public static final String App_Add                                    = "app-add.png";                                         //$NON-NLS-1$
   public static final String App_Add_2x                                 = "app-add-2x.png";                                      //$NON-NLS-1$
   public static final String App_Cancel_2                               = "16px-Crystal_Clear_action_button_cancel.png";         //$NON-NLS-1$
   public static final String App_Delete                                 = "delete.png";                                          //$NON-NLS-1$
   public static final String App_Delete_Disabled                        = "delete-disabled.png";                                 //$NON-NLS-1$
   public static final String App_Directory_CollatedTours                = "collated-tours.png";                                  //$NON-NLS-1$
   public static final String App_Directory_ReferenceTours               = "reference-tours.png";                                 //$NON-NLS-1$
   public static final String App_Directory_TaggedTours                  = "tagged-tours.png";                                    //$NON-NLS-1$
   public static final String App_Directory_TourBook                     = "tourbook-tours.png";                                  //$NON-NLS-1$
   public static final String App_Directory_TourComparisonTimeline       = "tour-map-statistic.png";                              //$NON-NLS-1$
   public static final String App_Directory_TourImport                   = "imported-tours.png";                                  //$NON-NLS-1$
   public static final String App_Edit                                   = "quick-edit.png";                                      //$NON-NLS-1$
   public static final String App_Edit_Disabled                          = "quick-edit-disabled.png";                             //$NON-NLS-1$
   public static final String App_EmptyIcon_Placeholder                  = "icon-placeholder.gif";                                //$NON-NLS-1$
   public static final String App_Hide                                   = "app-hide.png";                                        //$NON-NLS-1$
   public static final String App_OK                                     = "16px-Crystal_Clear_action_apply.png";                 //$NON-NLS-1$
   public static final String App_Placeholder16                          = "placeholder16.png";                                   //$NON-NLS-1$
   public static final String App_Refresh                                = "refresh.png";                                         //$NON-NLS-1$
   public static final String App_Refresh_Disabled                       = "refresh-disabled.png";                                //$NON-NLS-1$
   public static final String App_Refresh_All                            = "refresh-all.png";                                     //$NON-NLS-1$
   public static final String App_Refresh_All_Disabled                   = "refresh-all_disabled.png";                            //$NON-NLS-1$
   public static final String App_Refresh_NotAssessed                    = "refresh-not-assessed.png";                            //$NON-NLS-1$
   public static final String App_Refresh_NotAssessed_Disabled           = "refresh-not-assessed_disabled.png";                   //$NON-NLS-1$
   public static final String App_Refresh_Selected                       = "refresh-selected.png";                                //$NON-NLS-1$
   public static final String App_Refresh_Selected_Disabled              = "refresh-selected_disabled.png";                       //$NON-NLS-1$
   public static final String App_Remove                                 = "remove.png";                                          //$NON-NLS-1$
   public static final String App_Remove_Disabled                        = "remove-disabled.png";                                 //$NON-NLS-1$
   public static final String App_RemoveAll                              = "remove-all.png";                                      //$NON-NLS-1$
   public static final String App_RemoveAll_Disabled                     = "remove-all-disabled.png";                             //$NON-NLS-1$
   public static final String App_SequenceNumber                         = "app-sequence-number.png";                             //$NON-NLS-1$
   public static final String App_SequenceNumber_Disabled                = "app-sequence-number-disabled.png";                    //$NON-NLS-1$
   public static final String App_Show                                   = "app-show.png";                                        //$NON-NLS-1$
   public static final String App_Sort                                   = "app-sort.png";                                        //$NON-NLS-1$
   public static final String App_Sort_Disabled                          = "app-sort-disabled.png";                               //$NON-NLS-1$
   public static final String App_Today                                  = "today.png";                                           //$NON-NLS-1$
   public static final String App_Trash                                  = "trash.png";                                           //$NON-NLS-1$
   public static final String App_Trash_Disabled                         = "trash-disabled.png";                                  //$NON-NLS-1$
   public static final String App_Trash_Themed                           = "trash-blue.png";                                      //$NON-NLS-1$

   public static final String AdjustElevation                            = "adjust-altitude.png";                                 //$NON-NLS-1$
   public static final String AdjustElevation_Disabled                   = "adjust-altitude-disabled.png";                        //$NON-NLS-1$
   public static final String ArrowDown                                  = "arrow-down.png";                                      //$NON-NLS-1$
   public static final String ArrowDown_Blue                             = "arrow-down-blue.png";                                 //$NON-NLS-1$
   public static final String ArrowDown_Blue_Disabled                    = "arrow-down-blue-disabled.png";                        //$NON-NLS-1$
   public static final String ArrowUp                                    = "arrow-up.png";                                        //$NON-NLS-1$
   public static final String ArrowUp_Blue                               = "arrow-up-blue.png";                                   //$NON-NLS-1$
   public static final String ArrowUp_Blue_Disabled                      = "arrow-up-blue-disabled.png";                          //$NON-NLS-1$
   public static final String Calendar                                   = "calendar.png";                                        //$NON-NLS-1$
   public static final String Camera                                     = "camera.png";                                          //$NON-NLS-1$
   public static final String Checkbox_Checked                           = "checkbox-checked.png";                                //$NON-NLS-1$
   public static final String Checkbox_Checked_Disabled                  = "checkbox-checked-disabled.png";                       //$NON-NLS-1$
   public static final String Checkbox_Uncheck                           = "checkbox-unchecked.png";                              //$NON-NLS-1$
   public static final String Checkbox_Uncheck_Disabled                  = "checkbox-unchecked-disabled.png";                     //$NON-NLS-1$
   public static final String ConconiChart                               = "conconi-chart.png";                                   //$NON-NLS-1$
   public static final String CSVFormat                                  = "app-csv-format.png";                                  //$NON-NLS-1$
   public static final String CSVFormat_Disabled                         = "app-csv-format-disabled.png";                         //$NON-NLS-1$
   public static final String Cursor_Select                              = "cursor-select.png";                                   //$NON-NLS-1$
   public static final String EasyImport_Harddrive                       = "hard-drive.png";                                      //$NON-NLS-1$
   public static final String EditRow                                    = "edit-row.png";                                        //$NON-NLS-1$
   public static final String EditRow_Disabled                           = "edit-row-disabled.png";                               //$NON-NLS-1$
   public static final String EditTour                                   = "tour-editor.png";                                     //$NON-NLS-1$
   public static final String EditTour_Disabled                          = "write_obj_disabled.gif";                              //$NON-NLS-1$
   public static final String GeoCompare_PinComparedTour                 = "geo-compare-pin-compared-tour.png";                   //$NON-NLS-1$
   public static final String GeoCompare_PinComparedTour_Disabled        = "geo-compare-pin-compared-tour-disabled.png";          //$NON-NLS-1$
   public static final String GeoCompare_SelectComparedTour              = "geo-compare-select-compared-tour.png";                //$NON-NLS-1$
   public static final String GeoCompare_SelectComparedTour_Disabled     = "geo-compare-select-compared-tour-disabled.png";       //$NON-NLS-1$
   public static final String Graph                                      = "graph.png";                                           //$NON-NLS-1$
   public static final String GraphMinMax                                = "graph-min-max.png";                                   //$NON-NLS-1$
   public static final String GraphMinMax_Disabled                       = "graph-min-max-disabled.png";                          //$NON-NLS-1$
   public static final String Graph_Altimeter                            = "graph-altimeter.png";                                 //$NON-NLS-1$
   public static final String Graph_Altimeter_Disabled                   = "graph-altimeter-disabled.png";                        //$NON-NLS-1$
   public static final String Graph_Background                           = "graph-background.png";                                //$NON-NLS-1$
   public static final String Graph_Background_Disabled                  = "graph-background-disabled.png";                       //$NON-NLS-1$
   public static final String Graph_Cadence                              = "graph-cadence.png";                                   //$NON-NLS-1$
   public static final String Graph_Cadence_Disabled                     = "graph-cadence-disabled.png";                          //$NON-NLS-1$
   public static final String Graph_Disabled                             = "graph-disabled.png";                                  //$NON-NLS-1$
   public static final String Graph_Elevation                            = "graph-altitude.png";                                  //$NON-NLS-1$
   public static final String Graph_Elevation_Disabled                   = "graph-altitude-disabled.png";                         //$NON-NLS-1$
   public static final String Graph_Gears                                = "graph-gears.png";                                     //$NON-NLS-1$
   public static final String Graph_Gears_Disabled                       = "graph-gears-disabled.png";                            //$NON-NLS-1$
   public static final String Graph_Gradient                             = "graph-gradient.png";                                  //$NON-NLS-1$
   public static final String Graph_Gradient_Disabled                    = "graph-gradient-disabled.png";                         //$NON-NLS-1$
   public static final String Graph_Heartbeat                            = "graph-pulse.png";                                     //$NON-NLS-1$
   public static final String Graph_Heartbeat_Disabled                   = "graph-pulse-disabled.png";                            //$NON-NLS-1$
   public static final String Graph_Overlapped                           = "graph-overlapped.png";                                //$NON-NLS-1$
   public static final String Graph_Pace                                 = "graph-pace.png";                                      //$NON-NLS-1$
   public static final String Graph_Pace_Disabled                        = "graph-pace-disabled.png";                             //$NON-NLS-1$
   public static final String Graph_Pace_Interval                        = "graph-pace-interval.png";                             //$NON-NLS-1$
   public static final String Graph_Pace_Interval_Disabled               = "graph-pace-interval-disabled.png";                    //$NON-NLS-1$
   public static final String Graph_Pace_Summarized                      = "graph-pace-summarized.png";                           //$NON-NLS-1$
   public static final String Graph_Pace_Summarized_Disabled             = "graph-pace-summarized-disabled.png";                  //$NON-NLS-1$
   public static final String Graph_Power                                = "graph-power.png";                                     //$NON-NLS-1$
   public static final String Graph_Power_Disabled                       = "graph-power-disabled.png";                            //$NON-NLS-1$
   public static final String Graph_RunDyn_StanceTime                    = "graph-run-dyn-stance-time.png";                       //$NON-NLS-1$
   public static final String Graph_RunDyn_StanceTimeBalance             = "graph-run-dyn-stance-time-balance.png";               //$NON-NLS-1$
   public static final String Graph_RunDyn_StanceTimeBalance_Disabled    = "graph-run-dyn-stance-time-balance-disabled.png";      //$NON-NLS-1$
   public static final String Graph_RunDyn_StanceTime_Disabled           = "graph-run-dyn-stance-time-disabled.png";              //$NON-NLS-1$
   public static final String Graph_RunDyn_StepLength                    = "graph-run-dyn-step-length.png";                       //$NON-NLS-1$
   public static final String Graph_RunDyn_StepLength_Disabled           = "graph-run-dyn-step-length-disabled.png";              //$NON-NLS-1$
   public static final String Graph_RunDyn_VerticalOscillation           = "graph-run-dyn-vertical-oscillation.png";              //$NON-NLS-1$
   public static final String Graph_RunDyn_VerticalOscillation_Disabled  = "graph-run-dyn-vertical-oscillation-disabled.png";     //$NON-NLS-1$
   public static final String Graph_RunDyn_VerticalRatio                 = "graph-run-dyn-vertical-ratio.png";                    //$NON-NLS-1$
   public static final String Graph_RunDyn_VerticalRatio_Disabled        = "graph-run-dyn-vertical-ratio-disabled.png";           //$NON-NLS-1$
   public static final String Graph_Speed                                = "graph-speed.png";                                     //$NON-NLS-1$
   public static final String Graph_Speed_Disabled                       = "graph-speed-disabled.png";                            //$NON-NLS-1$
   public static final String Graph_Speed_Interval                       = "graph-speed-interval.png";                            //$NON-NLS-1$
   public static final String Graph_Speed_Interval_Disabled              = "graph-speed-interval-disabled.png";                   //$NON-NLS-1$
   public static final String Graph_Speed_Summarized                     = "graph-speed-summarized.png";                          //$NON-NLS-1$
   public static final String Graph_Speed_Summarized_Disabled            = "graph-speed-summarized-disabled.png";                 //$NON-NLS-1$
   public static final String Graph_Swim_Strokes                         = "graph-swim-strokes.png";                              //$NON-NLS-1$
   public static final String Graph_Swim_Strokes_Disabled                = "graph-swim-strokes-disabled.png";                     //$NON-NLS-1$
   public static final String Graph_Swim_Swolf                           = "graph-swim-swolf.png";                                //$NON-NLS-1$
   public static final String Graph_Swim_Swolf_Disabled                  = "graph-swim-swolf-disabled.png";                       //$NON-NLS-1$
   public static final String Graph_Temperature                          = "graph-temperature.png";                               //$NON-NLS-1$
   public static final String Graph_Temperature_Disabled                 = "graph-temperature-disabled.png";                      //$NON-NLS-1$
   public static final String Graph_TourCompare                          = "graph-tour-compare.png";                              //$NON-NLS-1$
   public static final String Graph_TourCompare_Disabled                 = "graph-tour-compare-disabled.png";                     //$NON-NLS-1$
   public static final String Graph_TourCompare_ByElevation              = "graph-tour-compare-elevation.png";                    //$NON-NLS-1$
   public static final String Graph_TourCompare_ByGeo                    = "graph-tour-compare-geo.png";                          //$NON-NLS-1$
   public static final String GroupValues                                = "app-group-values.png";                                //$NON-NLS-1$
   public static final String GroupValues_Disabled                       = "app-group-values-disabled.png";                       //$NON-NLS-1$
   public static final String HeartRateVariability                       = "heart-rate-variability.png";                          //$NON-NLS-1$
   public static final String Import_DashboardUI                         = "import-dashboard.png";                                //$NON-NLS-1$
   public static final String Import_Files                               = "import-get-tours.png";                                //$NON-NLS-1$
   public static final String Import_UI_Easy_Fancy                       = "import-ui-easy-fancy.png";                            //$NON-NLS-1$
   public static final String Import_UI_Easy_Fancy_Disabled              = "import-ui-easy-fancy-disabled.png";                   //$NON-NLS-1$
   public static final String Import_UI_Easy_Simple                      = "import-ui-easy-simple.png";                           //$NON-NLS-1$
   public static final String Import_UI_Easy_Simple_Disabled             = "import-ui-easy-simple-disabled.png";                  //$NON-NLS-1$
   public static final String Import_UI_Fossil                           = "import-ui-fossil.png";                                //$NON-NLS-1$
   public static final String Import_UI_Fossil_Disabled                  = "import-ui-fossil-disabled.png";                       //$NON-NLS-1$
   public static final String Map                                        = "map.png";                                             //$NON-NLS-1$
   public static final String Map2                                       = "map2-view.png";                                       //$NON-NLS-1$
   public static final String Map25                                      = "map25-view.png";                                      //$NON-NLS-1$
   public static final String Map3                                       = "map3-view.png";                                       //$NON-NLS-1$
   public static final String Map_ValuePoint                             = "map-marker-value-point.png";                          //$NON-NLS-1$
   public static final String Map_WayPoint                               = "waypoint-large.png";                                  //$NON-NLS-1$
   public static final String Map_WayPoint_Hovered                       = "waypoint-large-hovered.png";                          //$NON-NLS-1$
   public static final String Map3_DirectionArrow                        = "map3-direction-arrow.png";                            //$NON-NLS-1$
   public static final String Map3_DirectionArrow_Disabled               = "map3-direction-arrow-disabled.png";                   //$NON-NLS-1$
   public static final String Map3_Map3PropertiesView                    = "map3-properties.png";                                 //$NON-NLS-1$
   public static final String Map3_OpenGL_Version                        = "map3-opengl-version.png";                             //$NON-NLS-1$
   public static final String Map3_StatisticsView                        = "map3-statistics.png";                                 //$NON-NLS-1$
   public static final String MapBookmark                                = "map-bookmark.png";                                    //$NON-NLS-1$
   public static final String MapBookmark_Disabled                       = "map-bookmark-disabled.png";                           //$NON-NLS-1$
   public static final String MapBookmark_Location                       = "map-bookmark-location.png";                           //$NON-NLS-1$
   public static final String MapBookmark_New                            = "map-bookmark-new.png";                                //$NON-NLS-1$
   public static final String MapLayer                                   = "map-layer.png";                                       //$NON-NLS-1$
   public static final String MapLayer_Dark                              = "map-layer-dark.png";                                  //$NON-NLS-1$
   public static final String MapModel                                   = "map-model.png";                                       //$NON-NLS-1$
   public static final String MapModel_Disabled                          = "map-model-disabled.png";                              //$NON-NLS-1$
   public static final String MapModelCursor                             = "map-model-cursor.png";                                //$NON-NLS-1$
   public static final String MapModelCursor_Disabled                    = "map-model-cursor-disabled.png";                       //$NON-NLS-1$
   public static final String MapModelList                               = "map-model-list.png";                                  //$NON-NLS-1$
   public static final String MapModelList_Disabled                      = "map-model-list-disabled.png";                         //$NON-NLS-1$
   public static final String MapOptions                                 = "map-options.png";                                     //$NON-NLS-1$
   public static final String MapOptions_Dark                            = "map-options-dark.png";                                //$NON-NLS-1$
   public static final String MapOptions_Disabled                        = "map-options-disabled.png";                            //$NON-NLS-1$
   public static final String MapProvider                                = "change-map-provider.png";                             //$NON-NLS-1$
   public static final String MergeTours                                 = "merge-tours.png";                                     //$NON-NLS-1$
   public static final String ModelPlayer                                = "model-player.png";                                    //$NON-NLS-1$
   public static final String MyTourbook16                               = "tourbook16.png";                                      //$NON-NLS-1$
   public static final String POI_Anchor                                 = "anchor.png";                                          //$NON-NLS-1$
   public static final String POI_Car                                    = "car.png";                                             //$NON-NLS-1$
   public static final String POI_Cart                                   = "cart.png";                                            //$NON-NLS-1$
   public static final String POI_Disabled                               = "show-poi-disabled.png";                               //$NON-NLS-1$
   public static final String POI_Flag                                   = "flag_green.png";                                      //$NON-NLS-1$
   public static final String POI_House                                  = "house.png";                                           //$NON-NLS-1$
   public static final String POI_InMap                                  = "poi-in-map.png";                                      //$NON-NLS-1$
   public static final String POI_Soccer                                 = "sport_soccer.png";                                    //$NON-NLS-1$
   public static final String POI_Star                                   = "star.png";                                            //$NON-NLS-1$
   public static final String PhotoDirectoryView                         = "photo-directory.png";                                 //$NON-NLS-1$
   public static final String PhotoGallery_Horizontal                    = "photo-gallery-horizontal.png";                        //$NON-NLS-1$
   public static final String PhotoGallery_Vertical                      = "photo-gallery-vertical.png";                          //$NON-NLS-1$
   public static final String PhotoImage                                 = "photo-image.png";                                     //$NON-NLS-1$
   public static final String PhotoPhotos                                = "photo-photos.png";                                    //$NON-NLS-1$
   public static final String PhotoLinkWithTour                          = "photo-link-photo-with-tour.png";                      //$NON-NLS-1$
   public static final String PhotoSyncTour                              = "photo-sync-tour.png";                                 //$NON-NLS-1$
   public static final String PhotoTourPhotos                            = "photo-tour-photos.png";                               //$NON-NLS-1$
   public static final String PhotoTimeAdjustment                        = "photo-time-adjustment.png";                           //$NON-NLS-1$
   public static final String PhotoTimeAdjustment_Disabled               = "photo-time-adjustment-disabled.png";                  //$NON-NLS-1$
   public static final String PulseZones                                 = "pulse-zones.png";                                     //$NON-NLS-1$
   public static final String PulseZones_Disabled                        = "pulse-zones-disabled.png";                            //$NON-NLS-1$
   public static final String RawData_DeviceFolder_Off                   = "device-folder-off.png";                               //$NON-NLS-1$
   public static final String RawData_DeviceFolder_OK                    = "device-folder-OK.png";                                //$NON-NLS-1$
   public static final String RawData_DeviceFolder_Error                 = "device-folder-error.png";                             //$NON-NLS-1$
   public static final String RawData_DeviceFolder_IsChecking            = "device-folder-is-checking.png";                       //$NON-NLS-1$
   public static final String RawData_DeviceFolder_NotSetup              = "device-folder-not-setup.png";                         //$NON-NLS-1$
   public static final String RawData_Device_TurnOff                     = "device-turn-off.png";                                 //$NON-NLS-1$
   public static final String RawData_Device_TurnOn                      = "device-turn-on.png";                                  //$NON-NLS-1$
   public static final String RawData_Transfer                           = "device-synchronize.png";                              //$NON-NLS-1$
   public static final String RawData_TransferDirect                     = "device-synchronize-direct.png";                       //$NON-NLS-1$
   public static final String RefTour                                    = "tour-map-reftour.png";                                //$NON-NLS-1$
   public static final String RefTour_Layout_Flat                        = "reftour-layout-flat.png";                             //$NON-NLS-1$
   public static final String RefTour_Layout_Flat_Disabled               = "reftour-layout-flat-disabled.png";                    //$NON-NLS-1$
   public static final String RefTour_Layout_Hierarchical                = "reftour-layout-hierarchical.png";                     //$NON-NLS-1$
   public static final String RefTour_Layout_Hierarchical_Disabled       = "reftour-layout-hierarchical-disabled.png";            //$NON-NLS-1$
   public static final String RefTour_New                                = "tour-map-reftour-new.png";                            //$NON-NLS-1$
   public static final String RefTour_Statistic_Show_All_Values          = "ref-tour-statistic-show-all-values.png";              //$NON-NLS-1$
   public static final String RestoreTags                                = "restore-tour.png";                                    //$NON-NLS-1$
   public static final String RestoreTags_Disabled                       = "restore-tour-disabled.png";                           //$NON-NLS-1$
   public static final String RestoreTour                                = "restore-tour.png";                                    //$NON-NLS-1$
   public static final String RestoreTour_Disabled                       = "restore-tour-disabled.png";                           //$NON-NLS-1$
   public static final String SaveTags                                   = "save-tags.png";                                       //$NON-NLS-1$
   public static final String SaveTags_Disabled                          = "save-tags-disabled.png";                              //$NON-NLS-1$
   public static final String SaveTour                                   = "save-tour.png";                                       //$NON-NLS-1$
   public static final String SaveTour_Disabled                          = "save-tour-disabled.png";                              //$NON-NLS-1$
   public static final String Saved_MergedTour                           = "database-assigned-merge-tour.png";                    //$NON-NLS-1$
   public static final String Saved_MergedTour_Disabled                  = "database-disabled.png";                               //$NON-NLS-1$
   public static final String Saved_Tour                                 = "database.png";                                        //$NON-NLS-1$
   public static final String Saved_Tour_Disabled                        = "database-disabled.png";                               //$NON-NLS-1$
   public static final String Saved_Tour_OtherPerson                     = "database-other-person.png";                           //$NON-NLS-1$
   public static final String SearchExternal                             = "search-external.png";                                 //$NON-NLS-1$
   public static final String SearchExternal_Disabled                    = "search-external-disabled.png";                        //$NON-NLS-1$
   public static final String SearchPOI                                  = "search-poi.png";                                      //$NON-NLS-1$
   public static final String SearchTours                                = "search.png";                                          //$NON-NLS-1$
   public static final String SearchTours_ByLocation                     = "map-search-tour-by-location.png";                     //$NON-NLS-1$
   public static final String SearchTours_ByLocation_Scroll              = "map-search-tour-by-location-scroll.png";              //$NON-NLS-1$
   public static final String Sensor                                     = "sensor.png";                                          //$NON-NLS-1$
   public static final String Sensor_Disabled                            = "sensor-disabled.png";                                 //$NON-NLS-1$
   public static final String SensorChart                                = "sensor-chart.png";                                    //$NON-NLS-1$
   public static final String SensorChart_Disabled                       = "sensor-chart-disabled.png";                           //$NON-NLS-1$
   public static final String SetFavoritePosition                        = "map-set-favorite-position.png";                       //$NON-NLS-1$
   public static final String ShowFavoritePosition                       = "map-show-favorite-position.png";                      //$NON-NLS-1$
   public static final String ShowAllPhotos_InMap                        = "photo-show-all-photos.png";                           //$NON-NLS-1$
   public static final String ShowAllPhotos_InMap_Disabled               = "photo-show-all-photos-disabled.png";                  //$NON-NLS-1$
   public static final String ShowPhotos_InMap                           = "photo-photos.png";                                    //$NON-NLS-1$
   public static final String ShowPhotos_InMap_Disabled                  = "photo-photos-disabled.png";                           //$NON-NLS-1$
   public static final String ShowValuePoint                             = "map-marker-value-point-action.png";                   //$NON-NLS-1$
   public static final String Show_POI                                   = "show-poi.png";                                        //$NON-NLS-1$
   public static final String Smoothing                                  = "smooth.png";                                          //$NON-NLS-1$
   public static final String Smoothing_Disabled                         = "smooth-disabled.png";                                 //$NON-NLS-1$
   public static final String SplinePoint                                = "spline-point.png";                                    //$NON-NLS-1$
   public static final String State_AdjustTemperature                    = "state-temperature.png";                               //$NON-NLS-1$
   public static final String State_Copy                                 = "state-copy.png";                                      //$NON-NLS-1$
   public static final String State_Delete                               = "state-delete.png";                                    //$NON-NLS-1$
   public static final String State_DeletedTour_View                     = "state-deleted-tour-view.png";                         //$NON-NLS-1$
   public static final String State_Deleted_Backup                       = "state-delete-backup.png";                             //$NON-NLS-1$
   public static final String State_Deleted_Device                       = "state-delete-device.png";                             //$NON-NLS-1$
   public static final String State_Error                                = "state-error.png";                                     //$NON-NLS-1$
   public static final String State_Info                                 = "state-info.png";                                      //$NON-NLS-1$
   public static final String State_MovedTour                            = "state-moved-tour.png";                                //$NON-NLS-1$
   public static final String State_MovedTour_View                       = "state-moved-tour-view.png";                           //$NON-NLS-1$
   public static final String State_NotSavedInTour                       = "state-not-saved-in-tour.png";                         //$NON-NLS-1$
   public static final String State_OK                                   = "state-ok.png";                                        //$NON-NLS-1$
   public static final String State_RetrieveWeatherData                  = "state-weather.png";                                   //$NON-NLS-1$
   public static final String State_Save                                 = "state-save.png";                                      //$NON-NLS-1$
   public static final String State_SaveTour                             = "state-save-tour.png";                                 //$NON-NLS-1$
   public static final String State_SavedInTour                          = "state-saved-in-tour.png";                             //$NON-NLS-1$
   public static final String State_TourMarker                           = "state-tour-marker.png";                               //$NON-NLS-1$
   public static final String Statistic                                  = "statistics.png";                                      //$NON-NLS-1$
   public static final String StatisticValues                            = "statistic-values.png";                                //$NON-NLS-1$
   public static final String SyncGeoGraph_ByScale                       = "synch-geo-graph-byScale.png";                         //$NON-NLS-1$
   public static final String SyncGeoGraph_BySize                        = "synch-geo-graph-bySize.png";                          //$NON-NLS-1$
   public static final String SyncGraph_ByScale                          = "synch-graph-byScale.png";                             //$NON-NLS-1$
   public static final String SyncGraph_ByScale_Disabled                 = "synch-graph-byScale-disabled.png";                    //$NON-NLS-1$
   public static final String SyncGraph_BySize                           = "synch-graph-bySize.png";                              //$NON-NLS-1$
   public static final String SyncGraph_BySize_Disabled                  = "synch-graph-bySize-disabled.png";                     //$NON-NLS-1$
   public static final String SyncMap                                    = "sync-map.png";                                        //$NON-NLS-1$
   public static final String SyncMap_Disabled                           = "sync-map-disabled.png";                               //$NON-NLS-1$
   public static final String SyncStatistics                             = "synch-statistics.png";                                //$NON-NLS-1$
   public static final String SyncStatistics_Disabled                    = "synch-statistics-disabled.png";                       //$NON-NLS-1$
   public static final String SyncViews                                  = "synch-views.png";                                     //$NON-NLS-1$
   public static final String SyncWith_OtherMap                          = "sync-with-map.png";                                   //$NON-NLS-1$
   public static final String SyncWith_OtherMap_Disabled                 = "sync-with-map-disabled.png";                          //$NON-NLS-1$
   public static final String SyncWith_Photo                             = "photo-sync-map-with-photo.png";                       //$NON-NLS-1$
   public static final String SyncWith_Photo_Disabled                    = "photo-sync-map-with-photo-disabled.png";              //$NON-NLS-1$
   public static final String SyncWith_Slider_Centered                   = "synch-with-tour-slider-centered.png";                 //$NON-NLS-1$
   public static final String SyncWith_Slider_Centered_Disabled          = "synch-with-tour-slider-centered-disabled.png";        //$NON-NLS-1$
   public static final String SyncWith_ValuePoint                        = "sync-with-value-point.png";                           //$NON-NLS-1$
   public static final String SyncWith_ValuePoint_Disabled               = "sync-with-value-point-disabled.png";                  //$NON-NLS-1$
   public static final String SyncWith_Slider                            = "synch-with-tour-slider.png";                          //$NON-NLS-1$
   public static final String SyncWith_Slider_Disabled                   = "synch-with-tour-slider-disabled.png";                 //$NON-NLS-1$
   public static final String SyncWith_Tour                              = "synch-with-tour.png";                                 //$NON-NLS-1$
   public static final String SyncWith_Tour_Disabled                     = "synch-with-tour-disabled.png";                        //$NON-NLS-1$
   public static final String Tag                                        = "tag-tag.png";                                         //$NON-NLS-1$
   public static final String Tag_Category                               = "tag-category.png";                                    //$NON-NLS-1$
   public static final String Tag_Root                                   = "tag-tag-root.png";                                    //$NON-NLS-1$
   public static final String TagFilter_NoTours                          = "tour-tag-filter-no-tags.png";                         //$NON-NLS-1$
   public static final String TagLayout_Flat                             = "tag-layout-flat.png";                                 //$NON-NLS-1$
   public static final String TagLayout_Flat_Disabled                    = "tag-layout-flat-disabled.png";                        //$NON-NLS-1$
   public static final String TagLayout_Hierarchical                     = "tag-layout-hierarchical.png";                         //$NON-NLS-1$
   public static final String TagLayout_Hierarchical_Disabled            = "tag-layout-hierarchical-disabled.png";                //$NON-NLS-1$
   public static final String TagsChecked                                = "tags-checked.png";                                    //$NON-NLS-1$
   public static final String TagsChecked_Disabled                       = "tags-checked-disabled.png";                           //$NON-NLS-1$
   public static final String Tour_Duplicate                             = "tour-duplicate.png";                                  //$NON-NLS-1$
   public static final String Tour_Duplicate_Disabled                    = "tour-duplicate-disabled.png";                         //$NON-NLS-1$
   public static final String TourAnalyzer                               = "tour-analyzer.png";                                   //$NON-NLS-1$
   public static final String TourBlog                                   = "tour-blog.png";                                       //$NON-NLS-1$
   public static final String TourBook_Month                             = "tourbook-month.png";                                  //$NON-NLS-1$
   public static final String TourBook_NatTable                          = "tourbook-nattable.png";                               //$NON-NLS-1$
   public static final String TourBook_SelectAll                         = "tourbook-select-all.png";                             //$NON-NLS-1$
   public static final String TourBook_SelectAll_Disabled                = "tourbook-select-all-disabled.png";                    //$NON-NLS-1$
   public static final String TourBook_Week                              = "tourbook-week.png";                                   //$NON-NLS-1$
   public static final String TourChart                                  = "tour-chart.png";                                      //$NON-NLS-1$
   public static final String TourChart_Disabled                         = "tour-chart-disabled.png";                             //$NON-NLS-1$
   public static final String TourCompare_Timeline_Elevation             = "tour-compare-timeline-elevation.png";                 //$NON-NLS-1$
   public static final String TourCompare_Timeline_Geo                   = "tour-compare-timeline-geo.png";                       //$NON-NLS-1$
   public static final String TourCompare_ElevationCompare_Tool          = "tour-map-compare-result.png";                         //$NON-NLS-1$
   public static final String TourCompare_ElevationCompare_Tour          = "tour-compare-elevation-compared-tour.png";            //$NON-NLS-1$
   public static final String TourCompare_GeoCompare_Tool                = "geo-parts.png";                                       //$NON-NLS-1$
   public static final String TourCompare_GeoCompare_Tool_Disabled       = "tour-compare-geo-compare-tool-disabled.png";          //$NON-NLS-1$
   public static final String TourCompare_GeoCompare_Tour                = "tour-compare-geo-compared-tour.png";                  //$NON-NLS-1$
   public static final String TourCompare_GeoCompare_RefTour             = "tour-compare-geo-tour.png";                           //$NON-NLS-1$
   public static final String TourData                                   = "tour-data.png";                                       //$NON-NLS-1$
   public static final String TourElevationCompareFilter                 = "tour-elevation-compare-filter.png";                   //$NON-NLS-1$
   public static final String TourElevationCompareFilter_Saved           = "tour-elevation-compare-filter-saved.png";             //$NON-NLS-1$
   public static final String TourElevationCompareFilter_NotSaved        = "tour-elevation-compare-filter-not-saved.png";         //$NON-NLS-1$
   public static final String TourFilter                                 = "tour-filter.png";                                     //$NON-NLS-1$
   public static final String TourFilter_Disabled                        = "tour-filter-disabled.png";                            //$NON-NLS-1$
   public static final String TourFilter_Collected_All                   = "tour-filter-collected-all.png";                       //$NON-NLS-1$
   public static final String TourFilter_Collected_All_Disabled          = "tour-filter-collected-all-disabled.png";              //$NON-NLS-1$
   public static final String TourFilter_Collected_Not                   = "tour-filter-collected-not.png";                       //$NON-NLS-1$
   public static final String TourFilter_Collected_Not_Disabled          = "tour-filter-collected-not-disabled.png";              //$NON-NLS-1$
   public static final String TourFilter_Collected_Selected              = "tour-filter-collected-selected.png";                  //$NON-NLS-1$
   public static final String TourFilter_Collected_Selected_Disabled     = "tour-filter-collected-selected-disabled.png";         //$NON-NLS-1$
   public static final String TourFilter_TourWithPhotos                  = "tour-filter-tour-with-photos.png";                    //$NON-NLS-1$
   public static final String TourFilter_TourWithPhotos_Disabled         = "tour-filter-tour-with-photos-disabled.png";           //$NON-NLS-1$
   public static final String TourFilter_TourWithNotSavedPhotos          = "tour-filter-tour-with-not-saved-photos.png";          //$NON-NLS-1$
   public static final String TourFilter_TourWithNotSavedPhotos_Disabled = "tour-filter-tour-with-not-saved-photos-disabled.png"; //$NON-NLS-1$
   public static final String TourGeoFilter                              = "tour-geo-filter.png";                                 //$NON-NLS-1$
   public static final String TourInfo                                   = "tour-info.png";                                       //$NON-NLS-1$
   public static final String TourInfo_Disabled                          = "tour-info-disabled.png";                              //$NON-NLS-1$
   public static final String TourInfo_Hovered                           = "tour-info-hovered.png";                               //$NON-NLS-1$
   public static final String TourLog                                    = "tour-log.png";                                        //$NON-NLS-1$
   public static final String TourLog_Layout_Color                       = "tour-log-layout-color.png";                           //$NON-NLS-1$
   public static final String TourLog_Layout_Simple                      = "tour-log-layout-simple.png";                          //$NON-NLS-1$
   public static final String TourMarker                                 = "tour-marker.png";                                     //$NON-NLS-1$
   public static final String TourMarker_All                             = "tour-marker-all.png";                                 //$NON-NLS-1$
   public static final String TourMarker_Disabled                        = "tour-marker-disabled.png";                            //$NON-NLS-1$
   public static final String TourMarker_New                             = "tour-marker-new.png";                                 //$NON-NLS-1$
   public static final String TourMarker_New_Disabled                    = "tour-marker-new-disabled.png";                        //$NON-NLS-1$
   public static final String TourNew                                    = "tour-new.png";                                        //$NON-NLS-1$
   public static final String TourPauses                                 = "tour-pauses.png";                                     //$NON-NLS-1$
   public static final String TourPauses_Disabled                        = "tour-pauses-disabled.png";                            //$NON-NLS-1$
   public static final String TourSegmenter                              = "tour-segmenter.png";                                  //$NON-NLS-1$
   public static final String TourSegments                               = "tour-segments.png";                                   //$NON-NLS-1$
   public static final String TourSegments_Disabled                      = "tour-segments-disabled.png";                          //$NON-NLS-1$
   public static final String TourTagFilter                              = "tour-tag-filter.png";                                 //$NON-NLS-1$
   public static final String TourTagFilter_Disabled                     = "tour-tag-filter-disabled.png";                        //$NON-NLS-1$
   public static final String TourTags                                   = "tour-tags.png";                                       //$NON-NLS-1$
   public static final String TourType_Filter                            = "tour-type-filter.png";                                //$NON-NLS-1$
   public static final String TourType_Filter_System                     = "tour-type-filter-system.png";                         //$NON-NLS-1$
   public static final String TourViewer                                 = "tour-viewer.png";                                     //$NON-NLS-1$
   public static final String TourWayPoint                               = "tour-waypoint.png";                                   //$NON-NLS-1$
   public static final String TourWayPoint_Disabled                      = "tour-waypoint-disabled.png";                          //$NON-NLS-1$
   public static final String XAxis_ShowDistance                         = "x-axis-distance.png";                                 //$NON-NLS-1$
   public static final String XAxis_ShowDistance_Disabled                = "x-axis-distance-disabled.png";                        //$NON-NLS-1$
   public static final String XAxis_ShowDistance_Imperial                = "x-axis-distance-imperial.png";                        //$NON-NLS-1$
   public static final String XAxis_ShowDistance_Imperial_Disabled       = "x-axis-distance-imperial-disabled.png";               //$NON-NLS-1$
   public static final String XAxis_ShowDistance_NauticMile              = "x-axis-distance-nautical-mile.png";                   //$NON-NLS-1$
   public static final String XAxis_ShowDistance_NauticMile_Disabled     = "x-axis-distance-nautical-mile-disabled.png";          //$NON-NLS-1$
   public static final String XAxis_ShowTime                             = "x-axis-time.png";                                     //$NON-NLS-1$
   public static final String ZeroValues                                 = "app-zero-values.png";                                 //$NON-NLS-1$
   public static final String ZeroValues_Disabled                        = "app-zero-values-disabled.png";                        //$NON-NLS-1$
   public static final String Zoom_CenterBy_Map                          = "zoom-center-map.png";                                 //$NON-NLS-1$
   public static final String Zoom_CenterBy_Map_Disabled                 = "zoom-center-map-disabled.png";                        //$NON-NLS-1$
   public static final String Zoom_CenterBy_Mouse                        = "zoom-center-mouse.png";                               //$NON-NLS-1$
   public static final String Zoom_CenterBy_Mouse_Disabled               = "zoom-center-mouse-disabled.png";                      //$NON-NLS-1$
   public static final String Zoom_CenterBy_Tour                         = "zoom-center-tour.png";                                //$NON-NLS-1$
   public static final String Zoom_CenterBy_Tour_Disabled                = "zoom-center-tour-disabled.png";                       //$NON-NLS-1$
   public static final String Zoom_FitGraph                              = "zoom-fit-graph.gif";                                  //$NON-NLS-1$
   public static final String Zoom_In                                    = "zoom-in.png";                                         //$NON-NLS-1$
   public static final String Zoom_In_Disabled                           = "zoom-in-disabled.png";                                //$NON-NLS-1$
   public static final String Zoom_Out                                   = "zoom-out.png";                                        //$NON-NLS-1$
   public static final String Zoom_Out_Disabled                          = "zoom-out-disabled.png";                               //$NON-NLS-1$
   public static final String Zoom_Out_ToMinZoom                         = "zoom-fit-graph.gif";                                  //$NON-NLS-1$
   public static final String Zoom_Out_ToMinZoom_Disabled                = "zoom-fit-graph-disabled.gif";                         //$NON-NLS-1$
   public static final String Zoom_ShowEntireLayer                       = "map-show-entire-layer.png";                           //$NON-NLS-1$
   public static final String Zoom_ShowEntireMap                         = "zoom-show-entire-map.png";                            //$NON-NLS-1$
   public static final String Zoom_ShowEntireTour                        = "zoom-show-entire-tour.png";                           //$NON-NLS-1$
   public static final String Zoom_ShowEntireTour_Disabled               = "zoom-show-entire-tour-disabled.png";                  //$NON-NLS-1$

   private Images() {}
}
