////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.20Release
// Tag = $Name: AKW1_200 $
////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_CAPABILITIES_MESG_HPP)
#define FIT_CAPABILITIES_MESG_HPP

#include "fit_mesg.hpp"

namespace fit
{

class CapabilitiesMesg : public Mesg
{
   public:
      CapabilitiesMesg(void) : Mesg(Profile::MESG_CAPABILITIES)
      {
      }

      CapabilitiesMesg(const Mesg &mesg) : Mesg(mesg)
      {
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of languages
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumLanguages(void)
      {
         return GetFieldNumValues(0);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns languages field
      // Comment: Use language_bits_x types where x is index of array.
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8Z GetLanguages(FIT_UINT8 index)
      {
         return GetFieldUINT8ZValue(0, index);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set languages field
      // Comment: Use language_bits_x types where x is index of array.
      ///////////////////////////////////////////////////////////////////////
      void SetLanguages(FIT_UINT8 index, FIT_UINT8Z languages)
      {
         SetFieldUINT8ZValue(0, languages, index);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns number of sports
      ///////////////////////////////////////////////////////////////////////
      FIT_UINT8 GetNumSports(void)
      {
         return GetFieldNumValues(1);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns sports field
      // Comment: Use sport_bits_x types where x is index of array.
      ///////////////////////////////////////////////////////////////////////
      FIT_SPORT_BITS_0 GetSports(FIT_UINT8 index)
      {
         return GetFieldUINT8ZValue(1, index);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set sports field
      // Comment: Use sport_bits_x types where x is index of array.
      ///////////////////////////////////////////////////////////////////////
      void SetSports(FIT_UINT8 index, FIT_SPORT_BITS_0 sports)
      {
         SetFieldUINT8ZValue(1, sports, index);
      }

      ///////////////////////////////////////////////////////////////////////
      // Returns workouts_supported field
      ///////////////////////////////////////////////////////////////////////
      FIT_WORKOUT_CAPABILITIES GetWorkoutsSupported(void)
      {
         return GetFieldUINT32ZValue(21);
      }

      ///////////////////////////////////////////////////////////////////////
      // Set workouts_supported field
      ///////////////////////////////////////////////////////////////////////
      void SetWorkoutsSupported(FIT_WORKOUT_CAPABILITIES workoutsSupported)
      {
         SetFieldUINT32ZValue(21, workoutsSupported);
      }

};

} // namespace fit

#endif // !defined(FIT_CAPABILITIES_MESG_HPP)
