////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.ArrayList;

public class Factory {
   static public Mesg createMesg(Mesg mesg) {
      switch (mesg.getNum()) {       
         case MesgNum.FILE_ID:
            return new FileIdMesg(mesg);       
         case MesgNum.FILE_CREATOR:
            return new FileCreatorMesg(mesg);       
         case MesgNum.SOFTWARE:
            return new SoftwareMesg(mesg);       
         case MesgNum.CAPABILITIES:
            return new CapabilitiesMesg(mesg);       
         case MesgNum.FILE_CAPABILITIES:
            return new FileCapabilitiesMesg(mesg);       
         case MesgNum.MESG_CAPABILITIES:
            return new MesgCapabilitiesMesg(mesg);       
         case MesgNum.FIELD_CAPABILITIES:
            return new FieldCapabilitiesMesg(mesg);       
         case MesgNum.DEVICE_SETTINGS:
            return new DeviceSettingsMesg(mesg);       
         case MesgNum.USER_PROFILE:
            return new UserProfileMesg(mesg);       
         case MesgNum.HRM_PROFILE:
            return new HrmProfileMesg(mesg);       
         case MesgNum.ZONES_TARGET:
            return new ZonesTargetMesg(mesg);       
         case MesgNum.SPORT:
            return new SportMesg(mesg);       
         case MesgNum.HR_ZONE:
            return new HrZoneMesg(mesg);       
         case MesgNum.POWER_ZONE:
            return new PowerZoneMesg(mesg);       
         case MesgNum.MET_ZONE:
            return new MetZoneMesg(mesg);       
         case MesgNum.TRAINING_GOALS:
            return new TrainingGoalsMesg(mesg);       
         case MesgNum.ACTIVITY:
            return new ActivityMesg(mesg);       
         case MesgNum.SESSION:
            return new SessionMesg(mesg);       
         case MesgNum.LAP:
            return new LapMesg(mesg);       
         case MesgNum.RECORD:
            return new RecordMesg(mesg);       
         case MesgNum.EVENT:
            return new EventMesg(mesg);       
         case MesgNum.DEVICE_INFO:
            return new DeviceInfoMesg(mesg);       
         case MesgNum.WORKOUT:
            return new WorkoutMesg(mesg);       
         case MesgNum.WORKOUT_STEP:
            return new WorkoutStepMesg(mesg);       
         case MesgNum.TOTALS:
            return new TotalsMesg(mesg);       
         case MesgNum.WEIGHT_SCALE:
            return new WeightScaleMesg(mesg);       
         case MesgNum.BLOOD_PRESSURE:
            return new BloodPressureMesg(mesg);
         default:
            break;
      }
      return new Mesg("unknown", MesgNum.INVALID);
   }

   static public Mesg createMesg(int mesgNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum)
            return new Mesg(mesgs[i]);
      }
      return new Mesg("unknown", mesgNum);
   }

   static public Mesg createMesg(String mesgName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName))
            return new Mesg(mesgs[i]);
      }
      return new Mesg(mesgName, MesgNum.INVALID);
   }

   static public Field createField(String mesgName, String fieldName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName)) {
            return new Field(mesgs[i].getField(fieldName));
         }
      }
      return new Field(fieldName, Fit.FIELD_NUM_INVALID, 0, 1, 0, "");
   }

   static public Field createField(String mesgName, int fieldNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].name.equals(mesgName)) {
            return new Field(mesgs[i].getField(fieldNum));
         }
      }
      return new Field("unknown", fieldNum, 0, 1, 0, "");
   }

   static public Field createField(int mesgNum, int fieldNum) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum) {
            return new Field(mesgs[i].getField(fieldNum));
         }
      }
      return new Field("unknown", fieldNum, 0, 1, 0, "");
   }

   static public Field createField(int mesgNum, String fieldName) {
      for (int i = 0; i < mesgs.length; i++) {
         if (mesgs[i].num == mesgNum) {
            return new Field(mesgs[i].getField(fieldName));
         }
      }
      return new Field(fieldName, Fit.FIELD_NUM_INVALID, 0, 1, 0, "");
   }

   static public Field createField(String mesgName, String fieldName, ArrayList<Object> values) {
      Field field = createField(mesgName, fieldName);
      field.values = values;
      return field;
   }
   private static final Mesg mesgs[] = new Mesg[27];
   private static final MesgSubFieldMap mesgSubFieldMaps[] = new MesgSubFieldMap[27];

   static public void mapSubFields(Mesg mesg)
   {
      for (MesgSubFieldMap mesgSubFieldMap : mesgSubFieldMaps) {
         mesgSubFieldMap.map(mesg);
      }
   }

   static {
      int mesg_index = 0;
      int field_index;


      field_index = 0;
      mesgs[mesg_index] = new Mesg("file_id", MesgNum.FILE_ID);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.FILE_ID);
      mesgs[mesg_index].addField(new Field("type", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("manufacturer", 1, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("product", 2, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("garmin_product", 2, 132, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("garmin_product", 2, 1, 1);
      mesgSubFieldMaps[mesg_index].add("garmin_product", 2, 1, 15);
      mesgSubFieldMaps[mesg_index].add("garmin_product", 2, 1, 13);
      mesgs[mesg_index].addField(new Field("serial_number", 3, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("time_created", 4, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("number", 5, 132, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("file_creator", MesgNum.FILE_CREATOR);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.FILE_CREATOR);
      mesgs[mesg_index].addField(new Field("software_version", 0, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hardware_version", 1, 2, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("software", MesgNum.SOFTWARE);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.SOFTWARE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("version", 3, 132, 100, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("part_number", 5, 7, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("capabilities", MesgNum.CAPABILITIES);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.CAPABILITIES);
      mesgs[mesg_index].addField(new Field("workouts_supported", 21, 140, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("file_capabilities", MesgNum.FILE_CAPABILITIES);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.FILE_CAPABILITIES);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("type", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("flags", 1, 10, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("directory", 2, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_count", 3, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_size", 4, 134, 1, 0, "bytes"));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("mesg_capabilities", MesgNum.MESG_CAPABILITIES);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.MESG_CAPABILITIES);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("file", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("mesg_num", 1, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("count_type", 2, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("count", 3, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("num_per_file", 3, 132, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("num_per_file", 3, 2, 0);
      mesgs[mesg_index].addField(new Field("max_per_file", 3, 132, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("max_per_file", 3, 2, 1);
      mesgs[mesg_index].addField(new Field("max_per_file_type", 3, 132, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("max_per_file_type", 3, 2, 2);
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("field_capabilities", MesgNum.FIELD_CAPABILITIES);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.FIELD_CAPABILITIES);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("file", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("mesg_num", 1, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("field_num", 2, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("count", 3, 132, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("device_settings", MesgNum.DEVICE_SETTINGS);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.DEVICE_SETTINGS);
      mesgs[mesg_index].addField(new Field("utc_offset", 1, 134, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("user_profile", MesgNum.USER_PROFILE);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.USER_PROFILE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("friendly_name", 0, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("gender", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("age", 2, 2, 1, 0, "years"));
      field_index++;
      mesgs[mesg_index].addField(new Field("height", 3, 2, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("weight", 4, 132, 10, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("language", 5, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("elev_setting", 6, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("weight_setting", 7, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("resting_heart_rate", 8, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("default_max_running_heart_rate", 9, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("default_max_biking_heart_rate", 10, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("default_max_heart_rate", 11, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("hr_setting", 12, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("speed_setting", 13, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("dist_setting", 14, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("power_setting", 16, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("activity_class", 17, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("position_setting", 18, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("temperature_setting", 21, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("local_id", 22, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("global_id", 23, 13, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("hrm_profile", MesgNum.HRM_PROFILE);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.HRM_PROFILE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("enabled", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hrm_ant_id", 1, 139, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("zones_target", MesgNum.ZONES_TARGET);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.ZONES_TARGET);
      mesgs[mesg_index].addField(new Field("max_heart_rate", 1, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("threshold_heart_rate", 2, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("functional_threshold_power", 3, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hr_calc_type", 5, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("pwr_calc_type", 7, 0, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("sport", MesgNum.SPORT);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.SPORT);
      mesgs[mesg_index].addField(new Field("sport", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sub_sport", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 3, 7, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("hr_zone", MesgNum.HR_ZONE);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.HR_ZONE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("high_bpm", 1, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 2, 7, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("power_zone", MesgNum.POWER_ZONE);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.POWER_ZONE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("high_value", 1, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("name", 2, 7, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("met_zone", MesgNum.MET_ZONE);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.MET_ZONE);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("high_bpm", 1, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("calories", 2, 132, 10, 0, "kcal / min"));
      field_index++;
      mesgs[mesg_index].addField(new Field("fat_calories", 3, 2, 10, 0, "kcal / min"));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("training_goals", MesgNum.TRAINING_GOALS);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.TRAINING_GOALS);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sub_sport", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_date", 2, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("end_date", 3, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("type", 4, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("value", 5, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("repeat", 6, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("target_value", 7, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("recurrence", 8, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("recurrence_value", 9, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("enabled", 10, 0, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("activity", MesgNum.ACTIVITY);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.ACTIVITY);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_timer_time", 0, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("num_sessions", 1, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("type", 2, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event", 3, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_type", 4, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("local_timestamp", 5, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_group", 6, 2, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("session", MesgNum.SESSION);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.SESSION);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_time", 2, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_position_lat", 3, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_position_long", 4, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 5, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sub_sport", 6, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_elapsed_time", 7, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_timer_time", 8, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_distance", 9, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_cycles", 10, 134, 1, 0, "cycles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_strides", 10, 134, 1, 0, "strides"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("total_strides", 10, 5, 1);
      mesgs[mesg_index].addField(new Field("total_calories", 11, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_fat_calories", 13, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_speed", 14, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_speed", 15, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_heart_rate", 16, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_heart_rate", 17, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_cadence", 18, 2, 1, 0, "rpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_running_cadence", 18, 2, 1, 0, "strides/min"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("avg_running_cadence", 18, 5, 1);
      mesgs[mesg_index].addField(new Field("max_cadence", 19, 2, 1, 0, "rpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_running_cadence", 19, 2, 1, 0, "strides/min"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("max_running_cadence", 19, 5, 1);
      mesgs[mesg_index].addField(new Field("avg_power", 20, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_power", 21, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_ascent", 22, 132, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_descent", 23, 132, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_training_effect", 24, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("first_lap_index", 25, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("num_laps", 26, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_group", 27, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("trigger", 28, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("nec_lat", 29, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("nec_long", 30, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("swc_lat", 31, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("swc_long", 32, 133, 1, 0, "semicircles"));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("lap", MesgNum.LAP);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.LAP);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_time", 2, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_position_lat", 3, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("start_position_long", 4, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("end_position_lat", 5, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("end_position_long", 6, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_elapsed_time", 7, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_timer_time", 8, 134, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_distance", 9, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_cycles", 10, 134, 1, 0, "cycles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_strides", 10, 134, 1, 0, "strides"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("total_strides", 10, 25, 1);
      mesgs[mesg_index].addField(new Field("total_calories", 11, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_fat_calories", 12, 132, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_speed", 13, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_speed", 14, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_heart_rate", 15, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_heart_rate", 16, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_cadence", 17, 2, 1, 0, "rpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("avg_running_cadence", 17, 2, 1, 0, "strides/min"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("avg_running_cadence", 17, 25, 1);
      mesgs[mesg_index].addField(new Field("max_cadence", 18, 2, 1, 0, "rpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_running_cadence", 18, 2, 1, 0, "strides/min"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("max_running_cadence", 18, 25, 1);
      mesgs[mesg_index].addField(new Field("avg_power", 19, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("max_power", 20, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_ascent", 21, 132, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("total_descent", 22, 132, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("intensity", 23, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("lap_trigger", 24, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 25, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_group", 26, 2, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("record", MesgNum.RECORD);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.RECORD);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("position_lat", 0, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("position_long", 1, 133, 1, 0, "semicircles"));
      field_index++;
      mesgs[mesg_index].addField(new Field("altitude", 2, 132, 5, 500, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("heart_rate", 3, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("cadence", 4, 2, 1, 0, "rpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("distance", 5, 134, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("speed", 6, 132, 1000, 0, "m/s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("power", 7, 132, 1, 0, "watts"));
      field_index++;
      mesgs[mesg_index].addField(new Field("compressed_speed_distance", 8, 13, 1, 0, "")); 
      mesgs[mesg_index].fields.get(field_index).components.add(new FieldComponent(6, false, 12, 100, 0)); // speed 
      mesgs[mesg_index].fields.get(field_index).components.add(new FieldComponent(5, true, 12, 16, 0)); // distance
      field_index++;
      mesgs[mesg_index].addField(new Field("grade", 9, 131, 100, 0, "%"));
      field_index++;
      mesgs[mesg_index].addField(new Field("resistance", 10, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("time_from_course", 11, 133, 1000, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("cycle_length", 12, 2, 100, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("temperature", 13, 1, 1, 0, "°C"));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("event", MesgNum.EVENT);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.EVENT);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("event", 0, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("event_type", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("data16", 2, 132, 1, 0, "")); 
      mesgs[mesg_index].fields.get(field_index).components.add(new FieldComponent(3, false, 16, 1, 0)); // data
      field_index++;
      mesgs[mesg_index].addField(new Field("data", 3, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("timer_trigger", 3, 0, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("timer_trigger", 3, 0, 0);
      mesgs[mesg_index].addField(new Field("course_point", 3, 132, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("course_point", 3, 0, 10);
      mesgs[mesg_index].addField(new Field("battery_level", 3, 132, 1000, 0, "V"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("battery_level", 3, 0, 11);
      mesgs[mesg_index].addField(new Field("virtual_partner_speed", 3, 132, 1000, 0, "m/s"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("virtual_partner_speed", 3, 0, 12);
      mesgs[mesg_index].addField(new Field("hr_high_alert", 3, 2, 1, 0, "bpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("hr_high_alert", 3, 0, 13);
      mesgs[mesg_index].addField(new Field("hr_low_alert", 3, 2, 1, 0, "bpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("hr_low_alert", 3, 0, 14);
      mesgs[mesg_index].addField(new Field("speed_high_alert", 3, 132, 1000, 0, "m/s"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("speed_high_alert", 3, 0, 15);
      mesgs[mesg_index].addField(new Field("speed_low_alert", 3, 132, 1000, 0, "m/s"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("speed_low_alert", 3, 0, 16);
      mesgs[mesg_index].addField(new Field("cad_high_alert", 3, 132, 1, 0, "rpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("cad_high_alert", 3, 0, 17);
      mesgs[mesg_index].addField(new Field("cad_low_alert", 3, 132, 1, 0, "rpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("cad_low_alert", 3, 0, 18);
      mesgs[mesg_index].addField(new Field("power_high_alert", 3, 132, 1, 0, "watts"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("power_high_alert", 3, 0, 19);
      mesgs[mesg_index].addField(new Field("power_low_alert", 3, 132, 1, 0, "watts"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("power_low_alert", 3, 0, 20);
      mesgs[mesg_index].addField(new Field("time_duration_alert", 3, 134, 1000, 0, "s"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("time_duration_alert", 3, 0, 23);
      mesgs[mesg_index].addField(new Field("distance_duration_alert", 3, 134, 100, 0, "m"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("distance_duration_alert", 3, 0, 24);
      mesgs[mesg_index].addField(new Field("calorie_duration_alert", 3, 134, 1, 0, "calories"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("calorie_duration_alert", 3, 0, 25);
      mesgs[mesg_index].addField(new Field("fitness_equipment_state", 3, 0, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("fitness_equipment_state", 3, 0, 27);
      mesgs[mesg_index].addField(new Field("event_group", 4, 2, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("device_info", MesgNum.DEVICE_INFO);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.DEVICE_INFO);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("device_index", 0, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("device_type", 1, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("manufacturer", 2, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("serial_number", 3, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("product", 4, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("software_version", 5, 132, 100, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("hardware_version", 6, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("cum_operating_time", 7, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("battery_voltage", 10, 132, 256, 0, "V"));
      field_index++;
      mesgs[mesg_index].addField(new Field("battery_status", 11, 2, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("workout", MesgNum.WORKOUT);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.WORKOUT);
      mesgs[mesg_index].addField(new Field("sport", 4, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("capabilities", 5, 140, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("num_valid_steps", 6, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("wkt_name", 8, 7, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("workout_step", MesgNum.WORKOUT_STEP);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.WORKOUT_STEP);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("wkt_step_name", 0, 7, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("duration_type", 1, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("duration_value", 2, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("duration_time", 2, 134, 1000, 0, "s"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("duration_time", 2, 1, 0);
      mesgs[mesg_index].addField(new Field("duration_distance", 2, 134, 100, 0, "m"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("duration_distance", 2, 1, 1);
      mesgs[mesg_index].addField(new Field("duration_hr", 2, 134, 1, 0, "% or bpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("duration_hr", 2, 1, 2);
      mesgSubFieldMaps[mesg_index].add("duration_hr", 2, 1, 3);
      mesgs[mesg_index].addField(new Field("duration_calories", 2, 134, 1, 0, "calories"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("duration_calories", 2, 1, 4);
      mesgs[mesg_index].addField(new Field("duration_step", 2, 134, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("duration_step", 2, 1, 6);
      mesgSubFieldMaps[mesg_index].add("duration_step", 2, 1, 7);
      mesgSubFieldMaps[mesg_index].add("duration_step", 2, 1, 8);
      mesgSubFieldMaps[mesg_index].add("duration_step", 2, 1, 9);
      mesgSubFieldMaps[mesg_index].add("duration_step", 2, 1, 10);
      mesgSubFieldMaps[mesg_index].add("duration_step", 2, 1, 11);
      mesgSubFieldMaps[mesg_index].add("duration_step", 2, 1, 12);
      mesgSubFieldMaps[mesg_index].add("duration_step", 2, 1, 13);
      mesgs[mesg_index].addField(new Field("duration_power", 2, 134, 1, 0, "% or watts"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("duration_power", 2, 1, 14);
      mesgSubFieldMaps[mesg_index].add("duration_power", 2, 1, 15);
      mesgs[mesg_index].addField(new Field("target_type", 3, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("target_value", 4, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("target_hr_zone", 4, 134, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("target_hr_zone", 4, 3, 1);
      mesgs[mesg_index].addField(new Field("target_power_zone", 4, 134, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("target_power_zone", 4, 3, 4);
      mesgs[mesg_index].addField(new Field("repeat_steps", 4, 134, 1, 0, ""));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("repeat_steps", 4, 1, 6);
      mesgs[mesg_index].addField(new Field("repeat_time", 4, 134, 1000, 0, "s"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("repeat_time", 4, 1, 7);
      mesgs[mesg_index].addField(new Field("repeat_distance", 4, 134, 100, 0, "m"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("repeat_distance", 4, 1, 8);
      mesgs[mesg_index].addField(new Field("repeat_calories", 4, 134, 1, 0, "calories"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("repeat_calories", 4, 1, 9);
      mesgs[mesg_index].addField(new Field("repeat_hr", 4, 134, 1, 0, "% or bpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("repeat_hr", 4, 1, 10);
      mesgSubFieldMaps[mesg_index].add("repeat_hr", 4, 1, 11);
      mesgs[mesg_index].addField(new Field("repeat_power", 4, 134, 1, 0, "% or watts"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("repeat_power", 4, 1, 12);
      mesgSubFieldMaps[mesg_index].add("repeat_power", 4, 1, 13);
      mesgs[mesg_index].addField(new Field("custom_target_value_low", 5, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("custom_target_speed_low", 5, 134, 1000, 0, "m/s"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("custom_target_speed_low", 5, 3, 0);
      mesgs[mesg_index].addField(new Field("custom_target_heart_rate_low", 5, 134, 1, 0, "% or bpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("custom_target_heart_rate_low", 5, 3, 1);
      mesgs[mesg_index].addField(new Field("custom_target_cadence_low", 5, 134, 1, 0, "rpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("custom_target_cadence_low", 5, 3, 3);
      mesgs[mesg_index].addField(new Field("custom_target_power_low", 5, 134, 1, 0, "% or watts"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("custom_target_power_low", 5, 3, 4);
      mesgs[mesg_index].addField(new Field("custom_target_value_high", 6, 134, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("custom_target_speed_high", 6, 134, 1000, 0, "m/s"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("custom_target_speed_high", 6, 3, 0);
      mesgs[mesg_index].addField(new Field("custom_target_heart_rate_high", 6, 134, 1, 0, "% or bpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("custom_target_heart_rate_high", 6, 3, 1);
      mesgs[mesg_index].addField(new Field("custom_target_cadence_high", 6, 134, 1, 0, "rpm"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("custom_target_cadence_high", 6, 3, 3);
      mesgs[mesg_index].addField(new Field("custom_target_power_high", 6, 134, 1, 0, "% or watts"));
      field_index++;
      mesgSubFieldMaps[mesg_index].add("custom_target_power_high", 6, 3, 4);
      mesgs[mesg_index].addField(new Field("intensity", 7, 0, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("totals", MesgNum.TOTALS);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.TOTALS);
      mesgs[mesg_index].addField(new Field("message_index", 254, 132, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("timer_time", 0, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("distance", 1, 134, 1, 0, "m"));
      field_index++;
      mesgs[mesg_index].addField(new Field("calories", 2, 134, 1, 0, "kcal"));
      field_index++;
      mesgs[mesg_index].addField(new Field("sport", 3, 0, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("weight_scale", MesgNum.WEIGHT_SCALE);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.WEIGHT_SCALE);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("weight", 0, 132, 100, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("percent_fat", 1, 132, 100, 0, "%"));
      field_index++;
      mesgs[mesg_index].addField(new Field("percent_hydration", 2, 132, 100, 0, "%"));
      field_index++;
      mesgs[mesg_index].addField(new Field("visceral_fat_mass", 3, 132, 100, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("bone_mass", 4, 132, 100, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("muscle_mass", 5, 132, 100, 0, "kg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("basal_met", 7, 132, 4, 0, "kcal/day"));
      field_index++;
      mesgs[mesg_index].addField(new Field("physique_rating", 8, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("active_met", 9, 132, 4, 0, "kcal/day"));
      field_index++;
      mesgs[mesg_index].addField(new Field("metabolic_age", 10, 2, 1, 0, "years"));
      field_index++;
      mesgs[mesg_index].addField(new Field("visceral_fat_rating", 11, 2, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("user_profile_index", 12, 132, 1, 0, ""));
      field_index++;
      mesg_index++;
      field_index = 0;
      mesgs[mesg_index] = new Mesg("blood_pressure", MesgNum.BLOOD_PRESSURE);
      mesgSubFieldMaps[mesg_index] = new MesgSubFieldMap(MesgNum.BLOOD_PRESSURE);
      mesgs[mesg_index].addField(new Field("timestamp", 253, 134, 1, 0, "s"));
      field_index++;
      mesgs[mesg_index].addField(new Field("systolic_pressure", 0, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("diastolic_pressure", 1, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("mean_arterial_pressure", 2, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("map_3_sample_mean", 3, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("map_morning_values", 4, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("map_evening_values", 5, 132, 1, 0, "mmHg"));
      field_index++;
      mesgs[mesg_index].addField(new Field("heart_rate", 6, 2, 1, 0, "bpm"));
      field_index++;
      mesgs[mesg_index].addField(new Field("heart_rate_type", 7, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("status", 8, 0, 1, 0, ""));
      field_index++;
      mesgs[mesg_index].addField(new Field("user_profile_index", 9, 132, 1, 0, ""));
      field_index++;
      mesg_index++;
   }
}

