////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public class GarminProduct {
   public static final int HRM1 = 1; 
   public static final int AXH01 = 2; // AXH01 HRM chipset 
   public static final int AXB01 = 3; 
   public static final int AXB02 = 4; 
   public static final int HRM2SS = 5; 
   public static final int FR405 = 717; // Forerunner 405 
   public static final int FR50 = 782; // Forerunner 50 
   public static final int FR60 = 988; // Forerunner 60 
   public static final int FR310XT = 1018; // Forerunner 310 
   public static final int EDGE500 = 1036; 
   public static final int FR110 = 1124; // Forerunner 110 
   public static final int TRAINING_CENTER = 20119; 
   public static final int CONNECT = 65534; // Garmin Connect website 
   public static final int INVALID = Fit.UINT16_INVALID;








}
