////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.io.DataOutput;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;

public class Mesg {
   protected String name;
   protected int num;
   protected int localNum;
   protected ArrayList<Field> fields;
   protected long systemTimeOffset;

   public Mesg(final Mesg mesg) {
      this.fields = new ArrayList<Field>();

      if (mesg == null) {
         this.name = "unknown";
         this.num = MesgNum.INVALID;
         this.systemTimeOffset = 0;
         return;
      }

      this.name = mesg.name;
      this.num = mesg.num;
      this.localNum = mesg.localNum;
      this.systemTimeOffset = mesg.systemTimeOffset;
      for (Field field : mesg.fields) {
         if (field.getNumValues() > 0) {
            this.fields.add(new Field(field));
         }
      }
   }

   protected Mesg(String name, int num) {
      this.name = new String(name);
      this.num = num;
      this.localNum = 0;
      this.fields = new ArrayList<Field>();
      this.systemTimeOffset = 0;
   }

   protected int write(DataOutput out) {
      int mesg_size = 1;

      if (getNumFields() == 0)
         return 0;

      try {
         out.writeByte(localNum & Fit.HDR_TYPE_MASK); // Message record header.
      } catch (java.io.IOException e) {
         return 0;
      }

      for (Field field : fields) {
         int field_size = field.write(out);

         mesg_size += field_size;
      }

      return mesg_size;
   }

   public String getName() {
      return name;
   }

   public int getNum() {
      return num;
   }

   public boolean hasField(int num) {
      for (int i = 0; i < fields.size(); i++) {
         if (fields.get(i).num == num) {
            return true;
         }
      }

      return false;
   }

   public void addField(Field field) {
      fields.add(field);
   }

   public void setField(Field field) {
      for (int i = 0; i < fields.size(); i++) {
         if (fields.get(i).num == field.num) {
            fields.set(i, field);
            return;
         }
      }

      fields.add(field);
   }

   public int getNumFields() {
      return fields.size();
   }

   public Field getField(int num) {
      for (int i = 0; i < fields.size(); i++) {
         if (fields.get(i).num == num)
            return fields.get(i);
      }

      return null;
   }

   public Field getField(String name) {
      for (int i = 0; i < fields.size(); i++) {
         if (fields.get(i).name.equals(name))
            return fields.get(i);
      }

      return null;
   }

   public int getNumFieldValues(int num) {
      final Field field = getField(num);

      if (field == null)
         return 0;

      return field.getNumValues();
   }

   public int getNumFieldValues(String name) {
      final Field field = getField(name);

      if (field == null)
         return 0;

      return field.getNumValues();
   }

   public Object getFieldValue(int num) {
      return getFieldValue(num, 0);
   }

   public Object getFieldValue(int num, int index) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getValue(index);
   }

   public Object getFieldValue(String name) {
      return getFieldValue(name, 0);
   }

   public Object getFieldValue(String name, int index) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getValue(index);
   }

   public void setFieldValue(int num, Object value) {
      setFieldValue(num, 0, value);
   }

   public void setFieldValue(int num, int index, Object value) {
      Field field = getField(num);

      if (field == null) {
         field = Factory.createField(this.num, num);
         addField(field);
      }

      field.setValue(index, value);
   }

   public void setFieldValue(String name, Object value) {
      setFieldValue(name, 0, value);
   }

   public void setFieldValue(String name, int index, Object value) {
      Field field = getField(name);

      if (field == null) {
         field = Factory.createField(this.num, name);
         addField(field);
      }

      field.setValue(index, value);
   }

   public Long getFieldBitsValue(int num, int offset, int bits, boolean signed) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getBitsValue(offset, bits, signed);
   }

   public Long getFieldBitsValue(String name, int offset, int bits, boolean signed) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getBitsValue(offset, bits, signed);
   }

   public Byte getFieldByteValue(int num) {
      return getFieldByteValue(num, 0);
   }

   public Byte getFieldByteValue(int num, int index) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getByteValue(index);
   }

   public Byte getFieldByteValue(String name) {
      return getFieldByteValue(name, 0);
   }

   public Byte getFieldByteValue(String name, int index) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getByteValue(index);
   }

   public Short getFieldShortValue(int num) {
      return getFieldShortValue(num, 0);
   }

   public Short getFieldShortValue(int num, int index) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getShortValue(index);
   }

   public Short getFieldShortValue(String name) {
      return getFieldShortValue(name, 0);
   }

   public Short getFieldShortValue(String name, int index) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getShortValue(index);
   }

   public Integer getFieldIntegerValue(int num) {
      return getFieldIntegerValue(num, 0);
   }

   public Integer getFieldIntegerValue(int num, int index) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getIntegerValue(index);
   }

   public Integer getFieldIntegerValue(String name) {
      return getFieldIntegerValue(name, 0);
   }

   public Integer getFieldIntegerValue(String name, int index) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getIntegerValue(index);
   }

   public Long getFieldLongValue(int num) {
      return getFieldLongValue(num, 0);
   }

   public Long getFieldLongValue(int num, int index) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getLongValue(index);
   }

   public Long getFieldLongValue(String name) {
      return getFieldLongValue(name, 0);
   }

   public Long getFieldLongValue(String name, int index) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getLongValue(index);
   }

   public Float getFieldFloatValue(int num) {
      return getFieldFloatValue(num, 0);
   }

   public Float getFieldFloatValue(int num, int index) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getFloatValue(index);
   }

   public Float getFieldFloatValue(String name) {
      return getFieldFloatValue(name, 0);
   }

   public Float getFieldFloatValue(String name, int index) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getFloatValue(index);
   }

   public Double getFieldDoubleValue(int num) {
      return getFieldDoubleValue(num, 0);
   }

   public Double getFieldDoubleValue(int num, int index) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getDoubleValue(index);
   }

   public Double getFieldDoubleValue(String name) {
      return getFieldDoubleValue(name, 0);
   }

   public Double getFieldDoubleValue(String name, int index) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getDoubleValue(index);
   }

   public String getFieldStringValue(int num) {
      return getFieldStringValue(num, 0);
   }

   public String getFieldStringValue(int num, int index) {
      final Field field = getField(num);

      if (field == null)
         return null;

      return field.getStringValue(index);
   }

   public String getFieldStringValue(String name) {
      return getFieldStringValue(name, 0);
   }

   public String getFieldStringValue(String name, int index) {
      final Field field = getField(name);

      if (field == null)
         return null;

      return field.getStringValue(index);
   }

   public Collection<Field> getFields() {
      return Collections.unmodifiableCollection(fields);
   }

   public DateTime timestampToDateTime(Long timestamp) {
      DateTime dateTime;

      if (timestamp == null)
         return null;

      dateTime = new DateTime(timestamp);
      dateTime.convertSystemTimeToUTC(systemTimeOffset);

      return dateTime;
   }
   
   public void setLocalNum(int localNum)
   {
      if (localNum >= Fit.MAX_LOCAL_MESGS)
         throw new FitRuntimeException("Invalid local message number " + localNum + ".  Local message number must be < " + Fit.MAX_LOCAL_MESGS + ".");

      this.localNum = localNum;
   }

   public int getLocalNum()
   {
      return localNum;
   }
}
