////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public class UserLocalId {
   public static final int LOCAL_MIN = 0x01; 
   public static final int LOCAL_MAX = 0x0F; 
   public static final int STATIONARY_MIN = 0x10; 
   public static final int STATIONARY_MAX = 0xFF; 
   public static final int PORTABLE_MIN = 0x100; 
   public static final int PORTABLE_MAX = 0xFFFE; 
   public static final int INVALID = Fit.UINT16_INVALID;








}
