////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public class WorkoutMesg extends Mesg {


   public WorkoutMesg() {
      super(Factory.createMesg(MesgNum.WORKOUT));
   }

   public WorkoutMesg(final Mesg mesg) {
      super(mesg);
   }
   
   /**
    * Get sport field
    *
    * @return sport
    */
   public Sport getSport() {
      Short value = getFieldShortValue(4);
     if (value == null)
        return null;
      return Sport.getByValue(value);
   }

   /**
    * Set sport field
    *
    * @param sport
    */
   public void setSport(Sport sport) {
      setFieldValue("sport", sport.value);
   }   
   /**
    * Get capabilities field
    *
    * @return capabilities
    */
   public Long getCapabilities() {
      return getFieldLongValue(5);
   }

   /**
    * Set capabilities field
    *
    * @param capabilities
    */
   public void setCapabilities(Long capabilities) {
      setFieldValue("capabilities", capabilities);
   }   
   /**
    * Get num_valid_steps field
    * Comment: number of valid steps
    *
    * @return num_valid_steps
    */
   public Integer getNumValidSteps() {
      return getFieldIntegerValue(6);
   }

   /**
    * Set num_valid_steps field
    * Comment: number of valid steps
    *
    * @param numValidSteps
    */
   public void setNumValidSteps(Integer numValidSteps) {
      setFieldValue("num_valid_steps", numValidSteps);
   }   
   /**
    * Get wkt_name field
    *
    * @return wkt_name
    */
   public String getWktName() {
      return getFieldStringValue(8);
   }

   /**
    * Set wkt_name field
    *
    * @param wktName
    */
   public void setWktName(String wktName) {
      setFieldValue("wkt_name", wktName);
   }

}
